-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
-- Version: 2022.2.2
-- Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity crc24a is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    input_r_TVALID : IN STD_LOGIC;
    input_r_TREADY : OUT STD_LOGIC;
    input_r_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    input_r_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    input_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    output_r_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_r_TVALID : OUT STD_LOGIC;
    output_r_TREADY : IN STD_LOGIC );
end;


architecture behav of crc24a is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "crc24a_crc24a,hls_ip_2022_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.444000,HLS_SYN_LAT=16,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=87,HLS_SYN_LUT=875,HLS_VERSION=2022_2_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal input_r_TDATA_blk_n : STD_LOGIC;
    signal output_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tmp_last_V_reg_741 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_fu_261_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_reg_746 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_91_reg_752 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_92_reg_758 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_93_reg_764 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_94_reg_770 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_95_reg_776 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_96_reg_782 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_97_reg_788 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_393_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_1_fu_438_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_2_fu_483_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_3_fu_528_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_ap_start : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_ap_done : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_ap_idle : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_ap_ready : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_31_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_31_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_98_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_98_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_97_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_97_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_28_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_28_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_96_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_96_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_95_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_95_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_94_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_94_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_93_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_93_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_92_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_92_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_22_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_22_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_21_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_21_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_91_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_91_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_90_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_90_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_18_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_18_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_17_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_17_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_89_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_89_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_15_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_15_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_14_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_14_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_88_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_88_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_87_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_87_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_11_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_11_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_10_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_10_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_9_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_9_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_8_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_8_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_86_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_86_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_6_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_6_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_5_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_5_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_4_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_4_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_3_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_3_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_2_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_2_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_1_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc24a_Pipeline_loop2_fu_207_crc_V_out_ap_vld : STD_LOGIC;
    signal grp_crc24a_Pipeline_loop2_fu_207_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call52 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal crc_V_31_loc_fu_184 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_98_loc_fu_180 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_97_loc_fu_176 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_28_loc_fu_172 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_96_loc_fu_168 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_95_loc_fu_164 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_94_loc_fu_160 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_93_loc_fu_156 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_92_loc_fu_152 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_22_loc_fu_148 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_21_loc_fu_144 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_91_loc_fu_140 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_90_loc_fu_136 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_18_loc_fu_132 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_17_loc_fu_128 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_89_loc_fu_124 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_15_loc_fu_120 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_14_loc_fu_116 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_88_loc_fu_112 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_87_loc_fu_108 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_11_loc_fu_104 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_10_loc_fu_100 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_9_loc_fu_96 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_8_loc_fu_92 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_86_loc_fu_88 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_6_loc_fu_84 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_5_loc_fu_80 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_4_loc_fu_76 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_3_loc_fu_72 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_2_loc_fu_68 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_1_loc_fu_64 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_loc_fu_60 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ret_V_12_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_11_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_10_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_9_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_8_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_7_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_6_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_output_r_U_apdone_blk : STD_LOGIC;
    signal ap_block_state7 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal regslice_both_input_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal input_r_TVALID_int_regslice : STD_LOGIC;
    signal input_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_input_r_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TKEEP_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_input_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TSTRB_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_input_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_input_r_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_last_V_U_ack_in : STD_LOGIC;
    signal output_r_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal output_r_TVALID_int_regslice : STD_LOGIC;
    signal output_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_output_r_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component crc24a_crc24a_Pipeline_loop2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        crc_V_85 : IN STD_LOGIC_VECTOR (0 downto 0);
        crc_V_84 : IN STD_LOGIC_VECTOR (0 downto 0);
        crc_V_83 : IN STD_LOGIC_VECTOR (0 downto 0);
        crc_V_82 : IN STD_LOGIC_VECTOR (0 downto 0);
        crc_V_81 : IN STD_LOGIC_VECTOR (0 downto 0);
        crc_V_80 : IN STD_LOGIC_VECTOR (0 downto 0);
        crc_V_79 : IN STD_LOGIC_VECTOR (0 downto 0);
        crc_V_78 : IN STD_LOGIC_VECTOR (0 downto 0);
        tmp_last_V : IN STD_LOGIC_VECTOR (0 downto 0);
        crc_V_31_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_31_out_ap_vld : OUT STD_LOGIC;
        crc_V_98_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_98_out_ap_vld : OUT STD_LOGIC;
        crc_V_97_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_97_out_ap_vld : OUT STD_LOGIC;
        crc_V_28_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_28_out_ap_vld : OUT STD_LOGIC;
        crc_V_96_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_96_out_ap_vld : OUT STD_LOGIC;
        crc_V_95_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_95_out_ap_vld : OUT STD_LOGIC;
        crc_V_94_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_94_out_ap_vld : OUT STD_LOGIC;
        crc_V_93_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_93_out_ap_vld : OUT STD_LOGIC;
        crc_V_92_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_92_out_ap_vld : OUT STD_LOGIC;
        crc_V_22_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_22_out_ap_vld : OUT STD_LOGIC;
        crc_V_21_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_21_out_ap_vld : OUT STD_LOGIC;
        crc_V_91_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_91_out_ap_vld : OUT STD_LOGIC;
        crc_V_90_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_90_out_ap_vld : OUT STD_LOGIC;
        crc_V_18_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_18_out_ap_vld : OUT STD_LOGIC;
        crc_V_17_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_17_out_ap_vld : OUT STD_LOGIC;
        crc_V_89_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_89_out_ap_vld : OUT STD_LOGIC;
        crc_V_15_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_15_out_ap_vld : OUT STD_LOGIC;
        crc_V_14_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_14_out_ap_vld : OUT STD_LOGIC;
        crc_V_88_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_88_out_ap_vld : OUT STD_LOGIC;
        crc_V_87_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_87_out_ap_vld : OUT STD_LOGIC;
        crc_V_11_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_11_out_ap_vld : OUT STD_LOGIC;
        crc_V_10_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_10_out_ap_vld : OUT STD_LOGIC;
        crc_V_9_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_9_out_ap_vld : OUT STD_LOGIC;
        crc_V_8_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_8_out_ap_vld : OUT STD_LOGIC;
        crc_V_86_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_86_out_ap_vld : OUT STD_LOGIC;
        crc_V_6_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_6_out_ap_vld : OUT STD_LOGIC;
        crc_V_5_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_5_out_ap_vld : OUT STD_LOGIC;
        crc_V_4_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_4_out_ap_vld : OUT STD_LOGIC;
        crc_V_3_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_3_out_ap_vld : OUT STD_LOGIC;
        crc_V_2_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_2_out_ap_vld : OUT STD_LOGIC;
        crc_V_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_1_out_ap_vld : OUT STD_LOGIC;
        crc_V_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        crc_V_out_ap_vld : OUT STD_LOGIC );
    end component;


    component crc24a_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_crc24a_Pipeline_loop2_fu_207 : component crc24a_crc24a_Pipeline_loop2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_crc24a_Pipeline_loop2_fu_207_ap_start,
        ap_done => grp_crc24a_Pipeline_loop2_fu_207_ap_done,
        ap_idle => grp_crc24a_Pipeline_loop2_fu_207_ap_idle,
        ap_ready => grp_crc24a_Pipeline_loop2_fu_207_ap_ready,
        crc_V_85 => crc_V_97_reg_788,
        crc_V_84 => crc_V_96_reg_782,
        crc_V_83 => crc_V_95_reg_776,
        crc_V_82 => crc_V_94_reg_770,
        crc_V_81 => crc_V_93_reg_764,
        crc_V_80 => crc_V_92_reg_758,
        crc_V_79 => crc_V_91_reg_752,
        crc_V_78 => crc_V_reg_746,
        tmp_last_V => tmp_last_V_reg_741,
        crc_V_31_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_31_out,
        crc_V_31_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_31_out_ap_vld,
        crc_V_98_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_98_out,
        crc_V_98_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_98_out_ap_vld,
        crc_V_97_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_97_out,
        crc_V_97_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_97_out_ap_vld,
        crc_V_28_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_28_out,
        crc_V_28_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_28_out_ap_vld,
        crc_V_96_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_96_out,
        crc_V_96_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_96_out_ap_vld,
        crc_V_95_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_95_out,
        crc_V_95_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_95_out_ap_vld,
        crc_V_94_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_94_out,
        crc_V_94_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_94_out_ap_vld,
        crc_V_93_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_93_out,
        crc_V_93_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_93_out_ap_vld,
        crc_V_92_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_92_out,
        crc_V_92_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_92_out_ap_vld,
        crc_V_22_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_22_out,
        crc_V_22_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_22_out_ap_vld,
        crc_V_21_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_21_out,
        crc_V_21_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_21_out_ap_vld,
        crc_V_91_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_91_out,
        crc_V_91_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_91_out_ap_vld,
        crc_V_90_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_90_out,
        crc_V_90_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_90_out_ap_vld,
        crc_V_18_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_18_out,
        crc_V_18_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_18_out_ap_vld,
        crc_V_17_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_17_out,
        crc_V_17_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_17_out_ap_vld,
        crc_V_89_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_89_out,
        crc_V_89_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_89_out_ap_vld,
        crc_V_15_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_15_out,
        crc_V_15_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_15_out_ap_vld,
        crc_V_14_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_14_out,
        crc_V_14_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_14_out_ap_vld,
        crc_V_88_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_88_out,
        crc_V_88_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_88_out_ap_vld,
        crc_V_87_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_87_out,
        crc_V_87_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_87_out_ap_vld,
        crc_V_11_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_11_out,
        crc_V_11_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_11_out_ap_vld,
        crc_V_10_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_10_out,
        crc_V_10_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_10_out_ap_vld,
        crc_V_9_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_9_out,
        crc_V_9_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_9_out_ap_vld,
        crc_V_8_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_8_out,
        crc_V_8_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_8_out_ap_vld,
        crc_V_86_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_86_out,
        crc_V_86_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_86_out_ap_vld,
        crc_V_6_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_6_out,
        crc_V_6_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_6_out_ap_vld,
        crc_V_5_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_5_out,
        crc_V_5_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_5_out_ap_vld,
        crc_V_4_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_4_out,
        crc_V_4_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_4_out_ap_vld,
        crc_V_3_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_3_out,
        crc_V_3_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_3_out_ap_vld,
        crc_V_2_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_2_out,
        crc_V_2_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_2_out_ap_vld,
        crc_V_1_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_1_out,
        crc_V_1_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_1_out_ap_vld,
        crc_V_out => grp_crc24a_Pipeline_loop2_fu_207_crc_V_out,
        crc_V_out_ap_vld => grp_crc24a_Pipeline_loop2_fu_207_crc_V_out_ap_vld);

    regslice_both_input_r_V_data_V_U : component crc24a_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TDATA,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_data_V_U_ack_in,
        data_out => input_r_TDATA_int_regslice,
        vld_out => input_r_TVALID_int_regslice,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_data_V_U_apdone_blk);

    regslice_both_input_r_V_keep_V_U : component crc24a_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TKEEP,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_keep_V_U_ack_in,
        data_out => input_r_TKEEP_int_regslice,
        vld_out => regslice_both_input_r_V_keep_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_keep_V_U_apdone_blk);

    regslice_both_input_r_V_strb_V_U : component crc24a_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TSTRB,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_strb_V_U_ack_in,
        data_out => input_r_TSTRB_int_regslice,
        vld_out => regslice_both_input_r_V_strb_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_strb_V_U_apdone_blk);

    regslice_both_input_r_V_last_V_U : component crc24a_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TLAST,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_last_V_U_ack_in,
        data_out => input_r_TLAST_int_regslice,
        vld_out => regslice_both_input_r_V_last_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_last_V_U_apdone_blk);

    regslice_both_output_r_U : component crc24a_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => output_r_TDATA_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => output_r_TREADY_int_regslice,
        data_out => output_r_TDATA,
        vld_out => regslice_both_output_r_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_crc24a_Pipeline_loop2_fu_207_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_crc24a_Pipeline_loop2_fu_207_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((input_r_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_crc24a_Pipeline_loop2_fu_207_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_crc24a_Pipeline_loop2_fu_207_ap_ready = ap_const_logic_1)) then 
                    grp_crc24a_Pipeline_loop2_fu_207_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_10_out_ap_vld = ap_const_logic_1))) then
                crc_V_10_loc_fu_100 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_10_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_11_out_ap_vld = ap_const_logic_1))) then
                crc_V_11_loc_fu_104 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_11_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_14_out_ap_vld = ap_const_logic_1))) then
                crc_V_14_loc_fu_116 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_14_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_15_out_ap_vld = ap_const_logic_1))) then
                crc_V_15_loc_fu_120 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_15_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_17_out_ap_vld = ap_const_logic_1))) then
                crc_V_17_loc_fu_128 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_17_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_18_out_ap_vld = ap_const_logic_1))) then
                crc_V_18_loc_fu_132 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_18_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_1_out_ap_vld = ap_const_logic_1))) then
                crc_V_1_loc_fu_64 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_21_out_ap_vld = ap_const_logic_1))) then
                crc_V_21_loc_fu_144 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_21_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_22_out_ap_vld = ap_const_logic_1))) then
                crc_V_22_loc_fu_148 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_22_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_28_out_ap_vld = ap_const_logic_1))) then
                crc_V_28_loc_fu_172 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_28_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_2_out_ap_vld = ap_const_logic_1))) then
                crc_V_2_loc_fu_68 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_2_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_31_out_ap_vld = ap_const_logic_1))) then
                crc_V_31_loc_fu_184 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_31_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_3_out_ap_vld = ap_const_logic_1))) then
                crc_V_3_loc_fu_72 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_3_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_4_out_ap_vld = ap_const_logic_1))) then
                crc_V_4_loc_fu_76 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_4_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_5_out_ap_vld = ap_const_logic_1))) then
                crc_V_5_loc_fu_80 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_5_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_6_out_ap_vld = ap_const_logic_1))) then
                crc_V_6_loc_fu_84 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_6_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_86_out_ap_vld = ap_const_logic_1))) then
                crc_V_86_loc_fu_88 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_86_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_87_out_ap_vld = ap_const_logic_1))) then
                crc_V_87_loc_fu_108 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_87_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_88_out_ap_vld = ap_const_logic_1))) then
                crc_V_88_loc_fu_112 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_88_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_89_out_ap_vld = ap_const_logic_1))) then
                crc_V_89_loc_fu_124 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_89_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_8_out_ap_vld = ap_const_logic_1))) then
                crc_V_8_loc_fu_92 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_8_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_90_out_ap_vld = ap_const_logic_1))) then
                crc_V_90_loc_fu_136 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_90_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_91_out_ap_vld = ap_const_logic_1))) then
                crc_V_91_loc_fu_140 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_91_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                crc_V_91_reg_752 <= input_r_TDATA_int_regslice(1 downto 1);
                crc_V_92_reg_758 <= input_r_TDATA_int_regslice(2 downto 2);
                crc_V_93_reg_764 <= input_r_TDATA_int_regslice(3 downto 3);
                crc_V_94_reg_770 <= input_r_TDATA_int_regslice(4 downto 4);
                crc_V_95_reg_776 <= input_r_TDATA_int_regslice(5 downto 5);
                crc_V_96_reg_782 <= input_r_TDATA_int_regslice(6 downto 6);
                crc_V_97_reg_788 <= input_r_TDATA_int_regslice(7 downto 7);
                crc_V_reg_746 <= crc_V_fu_261_p1;
                tmp_last_V_reg_741 <= input_r_TLAST_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_92_out_ap_vld = ap_const_logic_1))) then
                crc_V_92_loc_fu_152 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_92_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_93_out_ap_vld = ap_const_logic_1))) then
                crc_V_93_loc_fu_156 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_93_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_94_out_ap_vld = ap_const_logic_1))) then
                crc_V_94_loc_fu_160 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_94_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_95_out_ap_vld = ap_const_logic_1))) then
                crc_V_95_loc_fu_164 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_95_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_96_out_ap_vld = ap_const_logic_1))) then
                crc_V_96_loc_fu_168 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_96_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_97_out_ap_vld = ap_const_logic_1))) then
                crc_V_97_loc_fu_176 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_97_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_98_out_ap_vld = ap_const_logic_1))) then
                crc_V_98_loc_fu_180 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_98_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_9_out_ap_vld = ap_const_logic_1))) then
                crc_V_9_loc_fu_96 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_9_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_crc_V_out_ap_vld = ap_const_logic_1))) then
                crc_V_loc_fu_60 <= grp_crc24a_Pipeline_loop2_fu_207_crc_V_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, grp_crc24a_Pipeline_loop2_fu_207_ap_done, ap_CS_fsm_state2, regslice_both_output_r_U_apdone_blk, input_r_TVALID_int_regslice, output_r_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((input_r_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_crc24a_Pipeline_loop2_fu_207_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if ((not(((output_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_output_r_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, input_r_TVALID_int_regslice)
    begin
        if (((input_r_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_crc24a_Pipeline_loop2_fu_207_ap_done)
    begin
        if ((grp_crc24a_Pipeline_loop2_fu_207_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(output_r_TREADY_int_regslice)
    begin
        if ((output_r_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(output_r_TREADY_int_regslice)
    begin
        if ((output_r_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(output_r_TREADY_int_regslice)
    begin
        if ((output_r_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(output_r_TREADY_int_regslice)
    begin
        if ((output_r_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state7_blk_assign_proc : process(regslice_both_output_r_U_apdone_blk, output_r_TREADY_int_regslice)
    begin
        if (((output_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_output_r_U_apdone_blk = ap_const_logic_1))) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, input_r_TVALID_int_regslice)
    begin
                ap_block_state1 <= ((input_r_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call52_assign_proc : process(ap_start, input_r_TVALID_int_regslice)
    begin
                ap_block_state1_ignore_call52 <= ((input_r_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state7_assign_proc : process(regslice_both_output_r_U_apdone_blk, output_r_TREADY_int_regslice)
    begin
                ap_block_state7 <= ((output_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_output_r_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state7, regslice_both_output_r_U_apdone_blk, output_r_TREADY_int_regslice)
    begin
        if ((not(((output_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_output_r_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7, regslice_both_output_r_U_apdone_blk, output_r_TREADY_int_regslice)
    begin
        if ((not(((output_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_output_r_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    crc_V_fu_261_p1 <= input_r_TDATA_int_regslice(1 - 1 downto 0);
    grp_crc24a_Pipeline_loop2_fu_207_ap_start <= grp_crc24a_Pipeline_loop2_fu_207_ap_start_reg;

    input_r_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, input_r_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            input_r_TDATA_blk_n <= input_r_TVALID_int_regslice;
        else 
            input_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_r_TREADY <= regslice_both_input_r_V_data_V_U_ack_in;

    input_r_TREADY_int_regslice_assign_proc : process(ap_start, ap_CS_fsm_state1, input_r_TVALID_int_regslice)
    begin
        if ((not(((input_r_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_r_TREADY_int_regslice <= ap_const_logic_1;
        else 
            input_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    output_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            output_r_TDATA_blk_n <= output_r_TREADY_int_regslice;
        else 
            output_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_r_TDATA_int_regslice_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, p_Result_s_fu_393_p9, p_Result_1_fu_438_p9, p_Result_2_fu_483_p9, p_Result_3_fu_528_p9, output_r_TREADY_int_regslice)
    begin
        if ((output_r_TREADY_int_regslice = ap_const_logic_1)) then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                output_r_TDATA_int_regslice <= p_Result_3_fu_528_p9;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                output_r_TDATA_int_regslice <= p_Result_2_fu_483_p9;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                output_r_TDATA_int_regslice <= p_Result_1_fu_438_p9;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                output_r_TDATA_int_regslice <= p_Result_s_fu_393_p9;
            else 
                output_r_TDATA_int_regslice <= "XXXXXXXX";
            end if;
        else 
            output_r_TDATA_int_regslice <= "XXXXXXXX";
        end if; 
    end process;

    output_r_TVALID <= regslice_both_output_r_U_vld_out;

    output_r_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, output_r_TREADY_int_regslice)
    begin
        if ((((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            output_r_TVALID_int_regslice <= ap_const_logic_1;
        else 
            output_r_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_1_fu_438_p9 <= (((((((crc_V_15_loc_fu_120 & crc_V_14_loc_fu_116) & crc_V_88_loc_fu_112) & crc_V_87_loc_fu_108) & crc_V_11_loc_fu_104) & crc_V_10_loc_fu_100) & crc_V_9_loc_fu_96) & crc_V_8_loc_fu_92);
    p_Result_2_fu_483_p9 <= (((((((crc_V_92_loc_fu_152 & crc_V_22_loc_fu_148) & crc_V_21_loc_fu_144) & crc_V_91_loc_fu_140) & crc_V_90_loc_fu_136) & crc_V_18_loc_fu_132) & crc_V_17_loc_fu_128) & crc_V_89_loc_fu_124);
    p_Result_3_fu_528_p9 <= (((((((crc_V_31_loc_fu_184 & crc_V_98_loc_fu_180) & crc_V_97_loc_fu_176) & crc_V_28_loc_fu_172) & crc_V_96_loc_fu_168) & crc_V_95_loc_fu_164) & crc_V_94_loc_fu_160) & crc_V_93_loc_fu_156);
    p_Result_s_fu_393_p9 <= (((((((ret_V_12_fu_388_p2 & ret_V_11_fu_383_p2) & ret_V_10_fu_378_p2) & ret_V_9_fu_373_p2) & ret_V_8_fu_368_p2) & ret_V_7_fu_363_p2) & ret_V_6_fu_358_p2) & ret_V_fu_353_p2);
    ret_V_10_fu_378_p2 <= (crc_V_95_reg_776 xor crc_V_5_loc_fu_80);
    ret_V_11_fu_383_p2 <= (crc_V_96_reg_782 xor crc_V_6_loc_fu_84);
    ret_V_12_fu_388_p2 <= (crc_V_97_reg_788 xor crc_V_86_loc_fu_88);
    ret_V_6_fu_358_p2 <= (crc_V_91_reg_752 xor crc_V_1_loc_fu_64);
    ret_V_7_fu_363_p2 <= (crc_V_92_reg_758 xor crc_V_2_loc_fu_68);
    ret_V_8_fu_368_p2 <= (crc_V_93_reg_764 xor crc_V_3_loc_fu_72);
    ret_V_9_fu_373_p2 <= (crc_V_94_reg_770 xor crc_V_4_loc_fu_76);
    ret_V_fu_353_p2 <= (crc_V_reg_746 xor crc_V_loc_fu_60);
end behav;
