// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cyclicPrefixRemoval_cyclicPrefixRemoval,hls_ip_2022_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.999500,HLS_SYN_LAT=8803,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=121,HLS_SYN_LUT=179,HLS_VERSION=2022_2_2}" *)

module cyclicPrefixRemoval (
        ap_clk,
        ap_rst_n,
        inpstream_TVALID,
        oupstream_TREADY,
        inpstream_TDATA,
        inpstream_TREADY,
        oupstream_TDATA,
        oupstream_TVALID,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   inpstream_TVALID;
input   oupstream_TREADY;
input  [63:0] inpstream_TDATA;
output   inpstream_TREADY;
output  [63:0] oupstream_TDATA;
output   oupstream_TVALID;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_ready;
wire   [0:0] icmp_ln12_fu_79_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] or_ln17_reg_142;
wire    regslice_both_oupstream_U_apdone_blk;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
reg   [0:0] or_ln17_reg_142_pp0_iter1_reg;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    inpstream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    oupstream_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [63:0] inpstream_read_reg_137;
wire   [0:0] or_ln17_fu_115_p2;
reg   [13:0] i_1_fu_54;
wire   [13:0] i_fu_85_p2;
wire    ap_loop_init;
reg   [13:0] ap_sig_allocacmp_v_1;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln17_fu_91_p2;
wire   [0:0] icmp_ln17_1_fu_97_p2;
wire   [0:0] and_ln17_fu_103_p2;
wire   [0:0] icmp_ln17_2_fu_109_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    regslice_both_inpstream_U_apdone_blk;
wire   [63:0] inpstream_TDATA_int_regslice;
wire    inpstream_TVALID_int_regslice;
reg    inpstream_TREADY_int_regslice;
wire    regslice_both_inpstream_U_ack_in;
reg    oupstream_TVALID_int_regslice;
wire    oupstream_TREADY_int_regslice;
wire    regslice_both_oupstream_U_vld_out;
reg    ap_condition_158;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cyclicPrefixRemoval_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

cyclicPrefixRemoval_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

cyclicPrefixRemoval_regslice_both #(
    .DataWidth( 64 ))
regslice_both_inpstream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inpstream_TDATA),
    .vld_in(inpstream_TVALID),
    .ack_in(regslice_both_inpstream_U_ack_in),
    .data_out(inpstream_TDATA_int_regslice),
    .vld_out(inpstream_TVALID_int_regslice),
    .ack_out(inpstream_TREADY_int_regslice),
    .apdone_blk(regslice_both_inpstream_U_apdone_blk)
);

cyclicPrefixRemoval_regslice_both #(
    .DataWidth( 64 ))
regslice_both_oupstream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inpstream_read_reg_137),
    .vld_in(oupstream_TVALID_int_regslice),
    .ack_in(oupstream_TREADY_int_regslice),
    .data_out(oupstream_TDATA),
    .vld_out(regslice_both_oupstream_U_vld_out),
    .ack_out(oupstream_TREADY),
    .apdone_blk(regslice_both_oupstream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_158)) begin
        if ((icmp_ln12_fu_79_p2 == 1'd0)) begin
            i_1_fu_54 <= i_fu_85_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_54 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        or_ln17_reg_142_pp0_iter1_reg <= or_ln17_reg_142;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_fu_79_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inpstream_read_reg_137 <= inpstream_TDATA_int_regslice;
        or_ln17_reg_142 <= or_ln17_fu_115_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln12_fu_79_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_v_1 = 14'd0;
    end else begin
        ap_sig_allocacmp_v_1 = i_1_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln12_fu_79_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inpstream_TDATA_blk_n = inpstream_TVALID_int_regslice;
    end else begin
        inpstream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_fu_79_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inpstream_TREADY_int_regslice = 1'b1;
    end else begin
        inpstream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (or_ln17_reg_142_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (or_ln17_reg_142 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        oupstream_TDATA_blk_n = oupstream_TREADY_int_regslice;
    end else begin
        oupstream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_ln17_reg_142 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        oupstream_TVALID_int_regslice = 1'b1;
    end else begin
        oupstream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln17_fu_103_p2 = (icmp_ln17_fu_91_p2 & icmp_ln17_1_fu_97_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_oupstream_U_apdone_blk == 1'b1)) | ((or_ln17_reg_142_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (oupstream_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_oupstream_U_apdone_blk == 1'b1) | ((or_ln17_reg_142 == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0)))) | ((icmp_ln12_fu_79_p2 == 1'd0) & (inpstream_TVALID_int_regslice == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_oupstream_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((or_ln17_reg_142_pp0_iter1_reg == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_oupstream_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state2_io) | ((or_ln17_reg_142 == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0)))) | ((icmp_ln12_fu_79_p2 == 1'd0) & (inpstream_TVALID_int_regslice == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_oupstream_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((or_ln17_reg_142_pp0_iter1_reg == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_oupstream_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state2_io) | ((or_ln17_reg_142 == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0)))) | ((icmp_ln12_fu_79_p2 == 1'd0) & (inpstream_TVALID_int_regslice == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln12_fu_79_p2 == 1'd0) & (inpstream_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((or_ln17_reg_142 == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((regslice_both_oupstream_U_apdone_blk == 1'b1) | ((or_ln17_reg_142 == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state3_io = ((or_ln17_reg_142_pp0_iter1_reg == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((or_ln17_reg_142_pp0_iter1_reg == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_condition_158 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign i_fu_85_p2 = (ap_sig_allocacmp_v_1 + 14'd1);

assign icmp_ln12_fu_79_p2 = ((ap_sig_allocacmp_v_1 == 14'd8800) ? 1'b1 : 1'b0);

assign icmp_ln17_1_fu_97_p2 = ((i_fu_85_p2 < 14'd4417) ? 1'b1 : 1'b0);

assign icmp_ln17_2_fu_109_p2 = ((i_fu_85_p2 > 14'd4704) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_91_p2 = ((i_fu_85_p2 > 14'd320) ? 1'b1 : 1'b0);

assign inpstream_TREADY = regslice_both_inpstream_U_ack_in;

assign or_ln17_fu_115_p2 = (icmp_ln17_2_fu_109_p2 | and_ln17_fu_103_p2);

assign oupstream_TVALID = regslice_both_oupstream_U_vld_out;


reg find_kernel_block = 0;
// synthesis translate_off
`include "cyclicPrefixRemoval_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //cyclicPrefixRemoval

