// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="crc24a_crc24a,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.173000,HLS_SYN_LAT=113,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=146,HLS_SYN_LUT=1719,HLS_VERSION=2022_2}" *)

module crc24a (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_TDATA,
        a_TVALID,
        a_TREADY,
        c_TDATA,
        c_TVALID,
        c_TREADY,
        last_TDATA,
        last_TVALID,
        last_TREADY
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] a_TDATA;
input   a_TVALID;
output   a_TREADY;
output  [63:0] c_TDATA;
output   c_TVALID;
input   c_TREADY;
output  [7:0] last_TDATA;
output   last_TVALID;
input   last_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg last_TVALID;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    last_TDATA_blk_n;
wire    ap_CS_fsm_state4;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_return;
reg   [0:0] targetBlock_reg_1985;
wire    ap_CS_fsm_state7;
wire   [0:0] and_ln60_fu_1103_p2;
reg   [0:0] and_ln60_reg_1993;
wire    ap_CS_fsm_state8;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_start;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_done;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_idle;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_ready;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_a_TREADY;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09814_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09814_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09811_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09811_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09808_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09808_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09805_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09805_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09802_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09802_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09799_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09799_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09796_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09796_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09793_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09793_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09790_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09790_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09787_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09787_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09784_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09784_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09781_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09781_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09778_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09778_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09775_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09775_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09772_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09772_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09769_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09769_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09766_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09766_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09763_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09763_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09760_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09760_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09757_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09757_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09754_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09754_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09751_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09751_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09748_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09748_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09745_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09745_out_ap_vld;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_start;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_done;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_idle;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_ready;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out1;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out1_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out2;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out2_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out3;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out3_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out4;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out4_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out5;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out5_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out6;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out6_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out7;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out7_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out8;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out8_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out9;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out9_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out10;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out10_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out11;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out11_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out12;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out12_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out13;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out13_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out14;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out14_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out15;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out15_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out16;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out16_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out17;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out17_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out18;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out18_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out19;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out19_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out20;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out20_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out21;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out21_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out22;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out22_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out23;
wire    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out23_ap_vld;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_start;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_done;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_idle;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_ready;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4752489189696_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4752489189696_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4682529693_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4682529693_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4582519690_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4582519690_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4475869687_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4475869687_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4369209684_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4369209684_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4262549681_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4262549681_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4155889678_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4155889678_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4049229675_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4049229675_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3949219672_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3949219672_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3849209669_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3849209669_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3742569666_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3742569666_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3635909663_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3635909663_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3535899660_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3535899660_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3435889657_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3435889657_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3329249654_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3329249654_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3229239651_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3229239651_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3129229648_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3129229648_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3022589645_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3022589645_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2915929642_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2915929642_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2815919639_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2815919639_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2715909636_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2715909636_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2615899633_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2615899633_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2515889630_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2515889630_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_249269627_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_249269627_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2382559624_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2382559624_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2176189621_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2176189621_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2175899618_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2175899618_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2069239615_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2069239615_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1962579612_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1962579612_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1855919609_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1855919609_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1749259606_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1749259606_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1443179603_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1443179603_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1442889600_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1442889600_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1442599597_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1442599597_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1335939594_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1335939594_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029859591_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029859591_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029569588_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029569588_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029279585_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029279585_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_723199582_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_723199582_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_722909579_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_722909579_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_722619576_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_722619576_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_615959573_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_615959573_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_110459570_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_110459570_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_110169567_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_110169567_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19879564_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19879564_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19589561_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19589561_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19299558_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19299558_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_09555_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_09555_out_ap_vld;
wire    grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_start;
wire    grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_done;
wire    grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_idle;
wire    grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_ready;
wire   [5:0] grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_startIdx_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_startIdx_out_ap_vld;
wire   [0:0] grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_icmp_ln60_out;
wire    grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_icmp_ln60_out_ap_vld;
wire    grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_start;
wire    grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_done;
wire    grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_idle;
wire    grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_ready;
wire    grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_c_TREADY;
wire   [63:0] grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_c_TDATA;
wire    grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_c_TVALID;
reg    grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_start_reg;
reg    grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_start_reg;
wire    ap_CS_fsm_state6;
reg   [5:0] startIdx_loc_fu_48;
reg   [0:0] icmp_ln60_loc_fu_44;
reg    grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    regslice_both_c_U_apdone_blk;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_block_state3_on_subcall_done;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    regslice_both_a_U_apdone_blk;
wire   [63:0] a_TDATA_int_regslice;
wire    a_TVALID_int_regslice;
reg    a_TREADY_int_regslice;
wire    regslice_both_a_U_ack_in;
wire    c_TREADY_int_regslice;
wire    regslice_both_c_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_start_reg = 1'b0;
#0 grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_start_reg = 1'b0;
#0 grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_start_reg = 1'b0;
#0 grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_start_reg = 1'b0;
#0 grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_start_reg = 1'b0;
end

crc24a_crc24a_Pipeline_VITIS_LOOP_20_1 grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_start),
    .ap_done(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_done),
    .ap_idle(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_idle),
    .ap_ready(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_ready),
    .a_TVALID(a_TVALID_int_regslice),
    .a_TDATA(a_TDATA_int_regslice),
    .a_TREADY(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_a_TREADY),
    .p_0_7_0_0_09814_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09814_out),
    .p_0_7_0_0_09814_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09814_out_ap_vld),
    .p_0_6_0_0_09811_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09811_out),
    .p_0_6_0_0_09811_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09811_out_ap_vld),
    .p_0_5_0_0_09808_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09808_out),
    .p_0_5_0_0_09808_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09808_out_ap_vld),
    .p_0_4_0_0_09805_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09805_out),
    .p_0_4_0_0_09805_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09805_out_ap_vld),
    .p_0_3_0_0_09802_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09802_out),
    .p_0_3_0_0_09802_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09802_out_ap_vld),
    .p_0_2_0_0_09799_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09799_out),
    .p_0_2_0_0_09799_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09799_out_ap_vld),
    .p_0_1_0_0_09796_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09796_out),
    .p_0_1_0_0_09796_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09796_out_ap_vld),
    .p_0_0_0_0_09793_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09793_out),
    .p_0_0_0_0_09793_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09793_out_ap_vld),
    .p_0_7_0_0_09790_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09790_out),
    .p_0_7_0_0_09790_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09790_out_ap_vld),
    .p_0_6_0_0_09787_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09787_out),
    .p_0_6_0_0_09787_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09787_out_ap_vld),
    .p_0_5_0_0_09784_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09784_out),
    .p_0_5_0_0_09784_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09784_out_ap_vld),
    .p_0_4_0_0_09781_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09781_out),
    .p_0_4_0_0_09781_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09781_out_ap_vld),
    .p_0_3_0_0_09778_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09778_out),
    .p_0_3_0_0_09778_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09778_out_ap_vld),
    .p_0_2_0_0_09775_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09775_out),
    .p_0_2_0_0_09775_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09775_out_ap_vld),
    .p_0_1_0_0_09772_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09772_out),
    .p_0_1_0_0_09772_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09772_out_ap_vld),
    .p_0_0_0_0_09769_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09769_out),
    .p_0_0_0_0_09769_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09769_out_ap_vld),
    .p_0_7_0_0_09766_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09766_out),
    .p_0_7_0_0_09766_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09766_out_ap_vld),
    .p_0_6_0_0_09763_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09763_out),
    .p_0_6_0_0_09763_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09763_out_ap_vld),
    .p_0_5_0_0_09760_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09760_out),
    .p_0_5_0_0_09760_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09760_out_ap_vld),
    .p_0_4_0_0_09757_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09757_out),
    .p_0_4_0_0_09757_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09757_out_ap_vld),
    .p_0_3_0_0_09754_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09754_out),
    .p_0_3_0_0_09754_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09754_out_ap_vld),
    .p_0_2_0_0_09751_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09751_out),
    .p_0_2_0_0_09751_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09751_out_ap_vld),
    .p_0_1_0_0_09748_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09748_out),
    .p_0_1_0_0_09748_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09748_out_ap_vld),
    .p_0_0_0_0_09745_out(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09745_out),
    .p_0_0_0_0_09745_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09745_out_ap_vld)
);

crc24a_crc24a_Pipeline_VITIS_LOOP_42_3 grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_start),
    .ap_done(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_done),
    .ap_idle(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_idle),
    .ap_ready(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_ready),
    .p_out(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out),
    .p_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out_ap_vld),
    .p_out1(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out1),
    .p_out1_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out1_ap_vld),
    .p_out2(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out2),
    .p_out2_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out2_ap_vld),
    .p_out3(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out3),
    .p_out3_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out3_ap_vld),
    .p_out4(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out4),
    .p_out4_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out4_ap_vld),
    .p_out5(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out5),
    .p_out5_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out5_ap_vld),
    .p_out6(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out6),
    .p_out6_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out6_ap_vld),
    .p_out7(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out7),
    .p_out7_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out7_ap_vld),
    .p_out8(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out8),
    .p_out8_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out8_ap_vld),
    .p_out9(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out9),
    .p_out9_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out9_ap_vld),
    .p_out10(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out10),
    .p_out10_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out10_ap_vld),
    .p_out11(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out11),
    .p_out11_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out11_ap_vld),
    .p_out12(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out12),
    .p_out12_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out12_ap_vld),
    .p_out13(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out13),
    .p_out13_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out13_ap_vld),
    .p_out14(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out14),
    .p_out14_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out14_ap_vld),
    .p_out15(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out15),
    .p_out15_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out15_ap_vld),
    .p_out16(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out16),
    .p_out16_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out16_ap_vld),
    .p_out17(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out17),
    .p_out17_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out17_ap_vld),
    .p_out18(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out18),
    .p_out18_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out18_ap_vld),
    .p_out19(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out19),
    .p_out19_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out19_ap_vld),
    .p_out20(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out20),
    .p_out20_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out20_ap_vld),
    .p_out21(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out21),
    .p_out21_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out21_ap_vld),
    .p_out22(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out22),
    .p_out22_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out22_ap_vld),
    .p_out23(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out23),
    .p_out23_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out23_ap_vld)
);

crc24a_crc24a_Pipeline_VITIS_LOOP_48_4 grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_start),
    .ap_done(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_done),
    .ap_idle(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_idle),
    .ap_ready(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_ready),
    .p_reload(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out),
    .p_reload93(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out23),
    .p_reload92(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out22),
    .p_reload91(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out21),
    .p_reload90(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out20),
    .p_reload89(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out19),
    .p_reload88(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out18),
    .p_reload87(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out17),
    .p_reload86(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out16),
    .p_reload85(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out15),
    .p_reload84(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out14),
    .p_reload83(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out13),
    .p_reload82(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out12),
    .p_reload81(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out11),
    .p_reload80(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out10),
    .p_reload79(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out9),
    .p_reload78(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out8),
    .p_reload77(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out7),
    .p_reload76(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out6),
    .p_reload75(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out5),
    .p_reload74(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out4),
    .p_reload73(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out3),
    .p_reload72(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out2),
    .p_reload71(grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_p_out1),
    .p_0_7_0_0_09814_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09814_out),
    .p_0_6_0_0_09811_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09811_out),
    .p_0_5_0_0_09808_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09808_out),
    .p_0_4_0_0_09805_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09805_out),
    .p_0_3_0_0_09802_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09802_out),
    .p_0_2_0_0_09799_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09799_out),
    .p_0_1_0_0_09796_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09796_out),
    .p_0_0_0_0_09793_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09793_out),
    .p_0_7_0_0_09766_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09766_out),
    .p_0_6_0_0_09763_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09763_out),
    .p_0_5_0_0_09760_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09760_out),
    .p_0_4_0_0_09757_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09757_out),
    .p_0_3_0_0_09754_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09754_out),
    .p_0_2_0_0_09751_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09751_out),
    .p_0_1_0_0_09748_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09748_out),
    .p_0_0_0_0_09745_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09745_out),
    .p_0_7_0_0_09790_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_7_0_0_09790_out),
    .p_0_6_0_0_09787_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_6_0_0_09787_out),
    .p_0_5_0_0_09784_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_5_0_0_09784_out),
    .p_0_4_0_0_09781_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_4_0_0_09781_out),
    .p_0_3_0_0_09778_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_3_0_0_09778_out),
    .p_0_2_0_0_09775_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_2_0_0_09775_out),
    .p_0_1_0_0_09772_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_1_0_0_09772_out),
    .p_0_0_0_0_09769_reload(grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_p_0_0_0_0_09769_out),
    .mux_case_4752489189696_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4752489189696_out),
    .mux_case_4752489189696_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4752489189696_out_ap_vld),
    .mux_case_4682529693_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4682529693_out),
    .mux_case_4682529693_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4682529693_out_ap_vld),
    .mux_case_4582519690_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4582519690_out),
    .mux_case_4582519690_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4582519690_out_ap_vld),
    .mux_case_4475869687_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4475869687_out),
    .mux_case_4475869687_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4475869687_out_ap_vld),
    .mux_case_4369209684_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4369209684_out),
    .mux_case_4369209684_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4369209684_out_ap_vld),
    .mux_case_4262549681_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4262549681_out),
    .mux_case_4262549681_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4262549681_out_ap_vld),
    .mux_case_4155889678_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4155889678_out),
    .mux_case_4155889678_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4155889678_out_ap_vld),
    .mux_case_4049229675_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4049229675_out),
    .mux_case_4049229675_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4049229675_out_ap_vld),
    .mux_case_3949219672_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3949219672_out),
    .mux_case_3949219672_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3949219672_out_ap_vld),
    .mux_case_3849209669_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3849209669_out),
    .mux_case_3849209669_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3849209669_out_ap_vld),
    .mux_case_3742569666_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3742569666_out),
    .mux_case_3742569666_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3742569666_out_ap_vld),
    .mux_case_3635909663_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3635909663_out),
    .mux_case_3635909663_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3635909663_out_ap_vld),
    .mux_case_3535899660_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3535899660_out),
    .mux_case_3535899660_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3535899660_out_ap_vld),
    .mux_case_3435889657_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3435889657_out),
    .mux_case_3435889657_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3435889657_out_ap_vld),
    .mux_case_3329249654_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3329249654_out),
    .mux_case_3329249654_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3329249654_out_ap_vld),
    .mux_case_3229239651_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3229239651_out),
    .mux_case_3229239651_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3229239651_out_ap_vld),
    .mux_case_3129229648_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3129229648_out),
    .mux_case_3129229648_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3129229648_out_ap_vld),
    .mux_case_3022589645_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3022589645_out),
    .mux_case_3022589645_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3022589645_out_ap_vld),
    .mux_case_2915929642_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2915929642_out),
    .mux_case_2915929642_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2915929642_out_ap_vld),
    .mux_case_2815919639_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2815919639_out),
    .mux_case_2815919639_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2815919639_out_ap_vld),
    .mux_case_2715909636_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2715909636_out),
    .mux_case_2715909636_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2715909636_out_ap_vld),
    .mux_case_2615899633_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2615899633_out),
    .mux_case_2615899633_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2615899633_out_ap_vld),
    .mux_case_2515889630_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2515889630_out),
    .mux_case_2515889630_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2515889630_out_ap_vld),
    .mux_case_249269627_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_249269627_out),
    .mux_case_249269627_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_249269627_out_ap_vld),
    .conv4_i_2382559624_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2382559624_out),
    .conv4_i_2382559624_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2382559624_out_ap_vld),
    .conv4_i_2176189621_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2176189621_out),
    .conv4_i_2176189621_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2176189621_out_ap_vld),
    .conv4_i_2175899618_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2175899618_out),
    .conv4_i_2175899618_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2175899618_out_ap_vld),
    .conv4_i_2069239615_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2069239615_out),
    .conv4_i_2069239615_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2069239615_out_ap_vld),
    .conv4_i_1962579612_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1962579612_out),
    .conv4_i_1962579612_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1962579612_out_ap_vld),
    .conv4_i_1855919609_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1855919609_out),
    .conv4_i_1855919609_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1855919609_out_ap_vld),
    .conv4_i_1749259606_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1749259606_out),
    .conv4_i_1749259606_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1749259606_out_ap_vld),
    .conv4_i_1443179603_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1443179603_out),
    .conv4_i_1443179603_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1443179603_out_ap_vld),
    .conv4_i_1442889600_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1442889600_out),
    .conv4_i_1442889600_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1442889600_out_ap_vld),
    .conv4_i_1442599597_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1442599597_out),
    .conv4_i_1442599597_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1442599597_out_ap_vld),
    .conv4_i_1335939594_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1335939594_out),
    .conv4_i_1335939594_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1335939594_out_ap_vld),
    .conv4_i_1029859591_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029859591_out),
    .conv4_i_1029859591_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029859591_out_ap_vld),
    .conv4_i_1029569588_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029569588_out),
    .conv4_i_1029569588_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029569588_out_ap_vld),
    .conv4_i_1029279585_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029279585_out),
    .conv4_i_1029279585_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029279585_out_ap_vld),
    .conv4_i_723199582_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_723199582_out),
    .conv4_i_723199582_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_723199582_out_ap_vld),
    .conv4_i_722909579_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_722909579_out),
    .conv4_i_722909579_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_722909579_out_ap_vld),
    .conv4_i_722619576_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_722619576_out),
    .conv4_i_722619576_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_722619576_out_ap_vld),
    .conv4_i_615959573_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_615959573_out),
    .conv4_i_615959573_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_615959573_out_ap_vld),
    .conv4_i_110459570_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_110459570_out),
    .conv4_i_110459570_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_110459570_out_ap_vld),
    .conv4_i_110169567_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_110169567_out),
    .conv4_i_110169567_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_110169567_out_ap_vld),
    .conv4_i_19879564_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19879564_out),
    .conv4_i_19879564_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19879564_out_ap_vld),
    .conv4_i_19589561_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19589561_out),
    .conv4_i_19589561_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19589561_out_ap_vld),
    .conv4_i_19299558_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19299558_out),
    .conv4_i_19299558_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19299558_out_ap_vld),
    .mux_case_09555_out(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_09555_out),
    .mux_case_09555_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_09555_out_ap_vld)
);

crc24a_crc24a_Pipeline_VITIS_LOOP_60_6 grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_start),
    .ap_done(grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_done),
    .ap_idle(grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_idle),
    .ap_ready(grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_ready),
    .mux_case_09555_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_09555_out),
    .conv4_i_19299558_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19299558_out),
    .conv4_i_19589561_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19589561_out),
    .conv4_i_19879564_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19879564_out),
    .conv4_i_110169567_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_110169567_out),
    .conv4_i_110459570_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_110459570_out),
    .conv4_i_615959573_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_615959573_out),
    .conv4_i_722619576_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_722619576_out),
    .conv4_i_722909579_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_722909579_out),
    .conv4_i_723199582_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_723199582_out),
    .conv4_i_1029279585_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029279585_out),
    .conv4_i_1029569588_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029569588_out),
    .conv4_i_1029859591_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029859591_out),
    .conv4_i_1335939594_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1335939594_out),
    .conv4_i_1442599597_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1442599597_out),
    .conv4_i_1442889600_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1442889600_out),
    .conv4_i_1443179603_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1443179603_out),
    .conv4_i_1749259606_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1749259606_out),
    .conv4_i_1855919609_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1855919609_out),
    .conv4_i_1962579612_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1962579612_out),
    .conv4_i_2069239615_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2069239615_out),
    .conv4_i_2175899618_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2175899618_out),
    .conv4_i_2176189621_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2176189621_out),
    .conv4_i_2382559624_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2382559624_out),
    .mux_case_249269627_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_249269627_out),
    .mux_case_2515889630_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2515889630_out),
    .mux_case_2615899633_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2615899633_out),
    .mux_case_2715909636_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2715909636_out),
    .mux_case_2815919639_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2815919639_out),
    .mux_case_2915929642_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2915929642_out),
    .mux_case_3022589645_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3022589645_out),
    .mux_case_3129229648_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3129229648_out),
    .mux_case_3229239651_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3229239651_out),
    .mux_case_3329249654_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3329249654_out),
    .mux_case_3435889657_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3435889657_out),
    .mux_case_3535899660_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3535899660_out),
    .mux_case_3635909663_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3635909663_out),
    .mux_case_3742569666_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3742569666_out),
    .mux_case_3849209669_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3849209669_out),
    .mux_case_3949219672_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3949219672_out),
    .mux_case_4049229675_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4049229675_out),
    .mux_case_4155889678_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4155889678_out),
    .mux_case_4262549681_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4262549681_out),
    .mux_case_4369209684_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4369209684_out),
    .mux_case_4475869687_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4475869687_out),
    .mux_case_4582519690_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4582519690_out),
    .mux_case_4682529693_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4682529693_out),
    .mux_case_4752489189696_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4752489189696_out),
    .startIdx_out(grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_startIdx_out),
    .startIdx_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_startIdx_out_ap_vld),
    .icmp_ln60_out(grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_icmp_ln60_out),
    .icmp_ln60_out_ap_vld(grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_icmp_ln60_out_ap_vld),
    .ap_return(grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_return)
);

crc24a_crc24a_Pipeline_VITIS_LOOP_67_7 grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_start),
    .ap_done(grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_done),
    .ap_idle(grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_idle),
    .ap_ready(grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_ready),
    .c_TREADY(grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_c_TREADY),
    .startIdx_reload(startIdx_loc_fu_48),
    .icmp_ln60_lcssa(and_ln60_reg_1993),
    .mux_case_09555_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_09555_out),
    .conv4_i_19299558_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19299558_out),
    .conv4_i_19589561_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19589561_out),
    .conv4_i_19879564_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_19879564_out),
    .conv4_i_110169567_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_110169567_out),
    .conv4_i_110459570_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_110459570_out),
    .conv4_i_615959573_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_615959573_out),
    .conv4_i_722619576_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_722619576_out),
    .conv4_i_722909579_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_722909579_out),
    .conv4_i_723199582_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_723199582_out),
    .conv4_i_1029279585_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029279585_out),
    .conv4_i_1029569588_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029569588_out),
    .conv4_i_1029859591_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1029859591_out),
    .conv4_i_1335939594_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1335939594_out),
    .conv4_i_1442599597_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1442599597_out),
    .conv4_i_1442889600_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1442889600_out),
    .conv4_i_1443179603_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1443179603_out),
    .conv4_i_1749259606_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1749259606_out),
    .conv4_i_1855919609_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1855919609_out),
    .conv4_i_1962579612_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_1962579612_out),
    .conv4_i_2069239615_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2069239615_out),
    .conv4_i_2175899618_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2175899618_out),
    .conv4_i_2176189621_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2176189621_out),
    .conv4_i_2382559624_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_conv4_i_2382559624_out),
    .mux_case_249269627_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_249269627_out),
    .mux_case_2515889630_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2515889630_out),
    .mux_case_2615899633_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2615899633_out),
    .mux_case_2715909636_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2715909636_out),
    .mux_case_2815919639_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2815919639_out),
    .mux_case_2915929642_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_2915929642_out),
    .mux_case_3022589645_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3022589645_out),
    .mux_case_3129229648_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3129229648_out),
    .mux_case_3229239651_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3229239651_out),
    .mux_case_3329249654_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3329249654_out),
    .mux_case_3435889657_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3435889657_out),
    .mux_case_3535899660_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3535899660_out),
    .mux_case_3635909663_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3635909663_out),
    .mux_case_3742569666_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3742569666_out),
    .mux_case_3849209669_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3849209669_out),
    .mux_case_3949219672_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_3949219672_out),
    .mux_case_4049229675_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4049229675_out),
    .mux_case_4155889678_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4155889678_out),
    .mux_case_4262549681_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4262549681_out),
    .mux_case_4369209684_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4369209684_out),
    .mux_case_4475869687_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4475869687_out),
    .mux_case_4582519690_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4582519690_out),
    .mux_case_4682529693_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4682529693_out),
    .mux_case_4752489189696_reload(grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_mux_case_4752489189696_out),
    .c_TDATA(grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_c_TDATA),
    .c_TVALID(grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_c_TVALID)
);

crc24a_regslice_both #(
    .DataWidth( 64 ))
regslice_both_a_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(a_TDATA),
    .vld_in(a_TVALID),
    .ack_in(regslice_both_a_U_ack_in),
    .data_out(a_TDATA_int_regslice),
    .vld_out(a_TVALID_int_regslice),
    .ack_out(a_TREADY_int_regslice),
    .apdone_blk(regslice_both_a_U_apdone_blk)
);

crc24a_regslice_both #(
    .DataWidth( 64 ))
regslice_both_c_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_c_TDATA),
    .vld_in(grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_c_TVALID),
    .ack_in(c_TREADY_int_regslice),
    .data_out(c_TDATA),
    .vld_out(regslice_both_c_U_vld_out),
    .ack_out(c_TREADY),
    .apdone_blk(regslice_both_c_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_start_reg <= 1'b1;
        end else if ((grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_ready == 1'b1)) begin
            grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_start_reg <= 1'b1;
        end else if ((grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_ready == 1'b1)) begin
            grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_start_reg <= 1'b0;
    end else begin
        if (((last_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_start_reg <= 1'b1;
        end else if ((grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_ready == 1'b1)) begin
            grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_start_reg <= 1'b1;
        end else if ((grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_ready == 1'b1)) begin
            grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_start_reg <= 1'b1;
        end else if ((grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_ready == 1'b1)) begin
            grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        and_ln60_reg_1993 <= and_ln60_fu_1103_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_icmp_ln60_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        icmp_ln60_loc_fu_44 <= grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_icmp_ln60_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_startIdx_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        startIdx_loc_fu_48 <= grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_startIdx_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        targetBlock_reg_1985 <= grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_return;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        a_TREADY_int_regslice = grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_a_TREADY;
    end else begin
        a_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_c_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((last_TREADY == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (regslice_both_c_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (regslice_both_c_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        last_TDATA_blk_n = last_TREADY;
    end else begin
        last_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((last_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        last_TVALID = 1'b1;
    end else begin
        last_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((last_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (regslice_both_c_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_TREADY = regslice_both_a_U_ack_in;

assign and_ln60_fu_1103_p2 = (targetBlock_reg_1985 & icmp_ln60_loc_fu_44);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_done == 1'b0) | (grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign c_TVALID = regslice_both_c_U_vld_out;

assign grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_start = grp_crc24a_Pipeline_VITIS_LOOP_20_1_fu_444_ap_start_reg;

assign grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_start = grp_crc24a_Pipeline_VITIS_LOOP_42_3_fu_474_ap_start_reg;

assign grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_start = grp_crc24a_Pipeline_VITIS_LOOP_48_4_fu_502_ap_start_reg;

assign grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_start = grp_crc24a_Pipeline_VITIS_LOOP_60_6_fu_602_ap_start_reg;

assign grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_start = grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_ap_start_reg;

assign grp_crc24a_Pipeline_VITIS_LOOP_67_7_fu_656_c_TREADY = (c_TREADY_int_regslice & ap_CS_fsm_state9);

assign last_TDATA = 8'd1;


reg find_kernel_block = 0;
// synthesis translate_off
`include "crc24a_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //crc24a

