// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module crc24a_crc24a_Pipeline_VITIS_LOOP_60_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mux_case_09555_reload,
        conv4_i_19299558_reload,
        conv4_i_19589561_reload,
        conv4_i_19879564_reload,
        conv4_i_110169567_reload,
        conv4_i_110459570_reload,
        conv4_i_615959573_reload,
        conv4_i_722619576_reload,
        conv4_i_722909579_reload,
        conv4_i_723199582_reload,
        conv4_i_1029279585_reload,
        conv4_i_1029569588_reload,
        conv4_i_1029859591_reload,
        conv4_i_1335939594_reload,
        conv4_i_1442599597_reload,
        conv4_i_1442889600_reload,
        conv4_i_1443179603_reload,
        conv4_i_1749259606_reload,
        conv4_i_1855919609_reload,
        conv4_i_1962579612_reload,
        conv4_i_2069239615_reload,
        conv4_i_2175899618_reload,
        conv4_i_2176189621_reload,
        conv4_i_2382559624_reload,
        mux_case_249269627_reload,
        mux_case_2515889630_reload,
        mux_case_2615899633_reload,
        mux_case_2715909636_reload,
        mux_case_2815919639_reload,
        mux_case_2915929642_reload,
        mux_case_3022589645_reload,
        mux_case_3129229648_reload,
        mux_case_3229239651_reload,
        mux_case_3329249654_reload,
        mux_case_3435889657_reload,
        mux_case_3535899660_reload,
        mux_case_3635909663_reload,
        mux_case_3742569666_reload,
        mux_case_3849209669_reload,
        mux_case_3949219672_reload,
        mux_case_4049229675_reload,
        mux_case_4155889678_reload,
        mux_case_4262549681_reload,
        mux_case_4369209684_reload,
        mux_case_4475869687_reload,
        mux_case_4582519690_reload,
        mux_case_4682529693_reload,
        mux_case_4752489189696_reload,
        startIdx_out,
        startIdx_out_ap_vld,
        icmp_ln60_out,
        icmp_ln60_out_ap_vld,
        ap_return
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] mux_case_09555_reload;
input  [0:0] conv4_i_19299558_reload;
input  [0:0] conv4_i_19589561_reload;
input  [0:0] conv4_i_19879564_reload;
input  [0:0] conv4_i_110169567_reload;
input  [0:0] conv4_i_110459570_reload;
input  [0:0] conv4_i_615959573_reload;
input  [0:0] conv4_i_722619576_reload;
input  [0:0] conv4_i_722909579_reload;
input  [0:0] conv4_i_723199582_reload;
input  [0:0] conv4_i_1029279585_reload;
input  [0:0] conv4_i_1029569588_reload;
input  [0:0] conv4_i_1029859591_reload;
input  [0:0] conv4_i_1335939594_reload;
input  [0:0] conv4_i_1442599597_reload;
input  [0:0] conv4_i_1442889600_reload;
input  [0:0] conv4_i_1443179603_reload;
input  [0:0] conv4_i_1749259606_reload;
input  [0:0] conv4_i_1855919609_reload;
input  [0:0] conv4_i_1962579612_reload;
input  [0:0] conv4_i_2069239615_reload;
input  [0:0] conv4_i_2175899618_reload;
input  [0:0] conv4_i_2176189621_reload;
input  [0:0] conv4_i_2382559624_reload;
input  [0:0] mux_case_249269627_reload;
input  [0:0] mux_case_2515889630_reload;
input  [0:0] mux_case_2615899633_reload;
input  [0:0] mux_case_2715909636_reload;
input  [0:0] mux_case_2815919639_reload;
input  [0:0] mux_case_2915929642_reload;
input  [0:0] mux_case_3022589645_reload;
input  [0:0] mux_case_3129229648_reload;
input  [0:0] mux_case_3229239651_reload;
input  [0:0] mux_case_3329249654_reload;
input  [0:0] mux_case_3435889657_reload;
input  [0:0] mux_case_3535899660_reload;
input  [0:0] mux_case_3635909663_reload;
input  [0:0] mux_case_3742569666_reload;
input  [0:0] mux_case_3849209669_reload;
input  [0:0] mux_case_3949219672_reload;
input  [0:0] mux_case_4049229675_reload;
input  [0:0] mux_case_4155889678_reload;
input  [0:0] mux_case_4262549681_reload;
input  [0:0] mux_case_4369209684_reload;
input  [0:0] mux_case_4475869687_reload;
input  [0:0] mux_case_4582519690_reload;
input  [0:0] mux_case_4682529693_reload;
input  [0:0] mux_case_4752489189696_reload;
output  [5:0] startIdx_out;
output   startIdx_out_ap_vld;
output  [0:0] icmp_ln60_out;
output   icmp_ln60_out_ap_vld;
output  [0:0] ap_return;

reg ap_idle;
reg[5:0] startIdx_out;
reg startIdx_out_ap_vld;
reg[0:0] icmp_ln60_out;
reg icmp_ln60_out_ap_vld;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] tmp_1_fu_479_p50;
wire   [0:0] icmp_ln60_fu_467_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] ap_phi_mux_UnifiedRetVal_phi_fu_450_p4;
reg   [5:0] startIdx_fu_138;
wire   [5:0] add_ln62_fu_473_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_startIdx_1;
reg   [0:0] ap_return_preg;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_return_preg = 1'd0;
#0 ap_done_reg = 1'b0;
end

crc24a_mux_486_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 1 ),
    .din18_WIDTH( 1 ),
    .din19_WIDTH( 1 ),
    .din20_WIDTH( 1 ),
    .din21_WIDTH( 1 ),
    .din22_WIDTH( 1 ),
    .din23_WIDTH( 1 ),
    .din24_WIDTH( 1 ),
    .din25_WIDTH( 1 ),
    .din26_WIDTH( 1 ),
    .din27_WIDTH( 1 ),
    .din28_WIDTH( 1 ),
    .din29_WIDTH( 1 ),
    .din30_WIDTH( 1 ),
    .din31_WIDTH( 1 ),
    .din32_WIDTH( 1 ),
    .din33_WIDTH( 1 ),
    .din34_WIDTH( 1 ),
    .din35_WIDTH( 1 ),
    .din36_WIDTH( 1 ),
    .din37_WIDTH( 1 ),
    .din38_WIDTH( 1 ),
    .din39_WIDTH( 1 ),
    .din40_WIDTH( 1 ),
    .din41_WIDTH( 1 ),
    .din42_WIDTH( 1 ),
    .din43_WIDTH( 1 ),
    .din44_WIDTH( 1 ),
    .din45_WIDTH( 1 ),
    .din46_WIDTH( 1 ),
    .din47_WIDTH( 1 ),
    .din48_WIDTH( 6 ),
    .dout_WIDTH( 1 ))
mux_486_1_1_1_U148(
    .din0(mux_case_09555_reload),
    .din1(conv4_i_19299558_reload),
    .din2(conv4_i_19589561_reload),
    .din3(conv4_i_19879564_reload),
    .din4(conv4_i_110169567_reload),
    .din5(conv4_i_110459570_reload),
    .din6(conv4_i_615959573_reload),
    .din7(conv4_i_722619576_reload),
    .din8(conv4_i_722909579_reload),
    .din9(conv4_i_723199582_reload),
    .din10(conv4_i_1029279585_reload),
    .din11(conv4_i_1029569588_reload),
    .din12(conv4_i_1029859591_reload),
    .din13(conv4_i_1335939594_reload),
    .din14(conv4_i_1442599597_reload),
    .din15(conv4_i_1442889600_reload),
    .din16(conv4_i_1443179603_reload),
    .din17(conv4_i_1749259606_reload),
    .din18(conv4_i_1855919609_reload),
    .din19(conv4_i_1962579612_reload),
    .din20(conv4_i_2069239615_reload),
    .din21(conv4_i_2175899618_reload),
    .din22(conv4_i_2176189621_reload),
    .din23(conv4_i_2382559624_reload),
    .din24(mux_case_249269627_reload),
    .din25(mux_case_2515889630_reload),
    .din26(mux_case_2615899633_reload),
    .din27(mux_case_2715909636_reload),
    .din28(mux_case_2815919639_reload),
    .din29(mux_case_2915929642_reload),
    .din30(mux_case_3022589645_reload),
    .din31(mux_case_3129229648_reload),
    .din32(mux_case_3229239651_reload),
    .din33(mux_case_3329249654_reload),
    .din34(mux_case_3435889657_reload),
    .din35(mux_case_3535899660_reload),
    .din36(mux_case_3635909663_reload),
    .din37(mux_case_3742569666_reload),
    .din38(mux_case_3849209669_reload),
    .din39(mux_case_3949219672_reload),
    .din40(mux_case_4049229675_reload),
    .din41(mux_case_4155889678_reload),
    .din42(mux_case_4262549681_reload),
    .din43(mux_case_4369209684_reload),
    .din44(mux_case_4475869687_reload),
    .din45(mux_case_4582519690_reload),
    .din46(mux_case_4682529693_reload),
    .din47(mux_case_4752489189696_reload),
    .din48(ap_sig_allocacmp_startIdx_1),
    .dout(tmp_1_fu_479_p50)
);

crc24a_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((icmp_ln60_fu_467_p2 == 1'd1) | (tmp_1_fu_479_p50 == 1'd1)))) begin
            ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_450_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln60_fu_467_p2 == 1'd0) & (tmp_1_fu_479_p50 == 1'd0))) begin
            startIdx_fu_138 <= add_ln62_fu_473_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            startIdx_fu_138 <= 6'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((icmp_ln60_fu_467_p2 == 1'd1) | (tmp_1_fu_479_p50 == 1'd1)))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((icmp_ln60_fu_467_p2 == 1'd0) & (tmp_1_fu_479_p50 == 1'd1))) begin
            ap_phi_mux_UnifiedRetVal_phi_fu_450_p4 = 1'd0;
        end else if ((icmp_ln60_fu_467_p2 == 1'd1)) begin
            ap_phi_mux_UnifiedRetVal_phi_fu_450_p4 = 1'd1;
        end else begin
            ap_phi_mux_UnifiedRetVal_phi_fu_450_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_450_p4 = 'bx;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((icmp_ln60_fu_467_p2 == 1'd1) | (tmp_1_fu_479_p50 == 1'd1)))) begin
        ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_450_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_startIdx_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_startIdx_1 = startIdx_fu_138;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln60_fu_467_p2 == 1'd1)) begin
            icmp_ln60_out = 1'd1;
        end else if (((icmp_ln60_fu_467_p2 == 1'd0) & (tmp_1_fu_479_p50 == 1'd1))) begin
            icmp_ln60_out = 1'd0;
        end else begin
            icmp_ln60_out = 'bx;
        end
    end else begin
        icmp_ln60_out = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln60_fu_467_p2 == 1'd0) & (tmp_1_fu_479_p50 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln60_fu_467_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        icmp_ln60_out_ap_vld = 1'b1;
    end else begin
        icmp_ln60_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln60_fu_467_p2 == 1'd1)) begin
            startIdx_out = 6'd48;
        end else if (((icmp_ln60_fu_467_p2 == 1'd0) & (tmp_1_fu_479_p50 == 1'd1))) begin
            startIdx_out = ap_sig_allocacmp_startIdx_1;
        end else begin
            startIdx_out = 'bx;
        end
    end else begin
        startIdx_out = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln60_fu_467_p2 == 1'd0) & (tmp_1_fu_479_p50 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln60_fu_467_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        startIdx_out_ap_vld = 1'b1;
    end else begin
        startIdx_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln62_fu_473_p2 = (ap_sig_allocacmp_startIdx_1 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln60_fu_467_p2 = ((ap_sig_allocacmp_startIdx_1 == 6'd48) ? 1'b1 : 1'b0);

endmodule //crc24a_crc24a_Pipeline_VITIS_LOOP_60_6
