#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jun 27 16:05:50 IST 2023
# SW Build 3788238 on Tue Feb 21 19:59:23 MST 2023
#
# IP Build 3783773 on Tue Feb 21 23:41:56 MST 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim axistb_behav -key {Behavioral:sim_1:Functional:axistb} -tclbatch axistb.tcl -protoinst "protoinst_files/design_rtl_IP.protoinst" -view /home/sam-admin/git/Training/HLS_Vivado/A9/PART-2_RTL/rtl_a9/axistb_behav.wcfg -log simulate.log"
xsim axistb_behav -key {Behavioral:sim_1:Functional:axistb} -tclbatch axistb.tcl -protoinst "protoinst_files/design_rtl_IP.protoinst" -view /home/sam-admin/git/Training/HLS_Vivado/A9/PART-2_RTL/rtl_a9/axistb_behav.wcfg -log simulate.log

