// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mul,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.447143,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=0,HLS_SYN_LUT=36,HLS_VERSION=2018_3}" *)

module mul (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_V,
        b_V,
        c_V
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [27:0] a_V;
input  [27:0] b_V;
output  [55:0] c_V;

wire  signed [27:0] r_V_1_fu_51_p0;
wire  signed [27:0] r_V_1_fu_51_p1;

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign c_V = ($signed(r_V_1_fu_51_p0) * $signed(r_V_1_fu_51_p1));

assign r_V_1_fu_51_p0 = b_V;

assign r_V_1_fu_51_p1 = a_V;

endmodule //mul
