// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cyclicPrefixRemoval_cyclicPrefixRemoval,hls_ip_2022_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.797500,HLS_SYN_LAT=8803,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=85,HLS_SYN_LUT=139,HLS_VERSION=2022_2_2}" *)

module cyclicPrefixRemoval (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inpstream_TVALID,
        oupstream_TREADY,
        inpstream_TDATA,
        inpstream_TREADY,
        oupstream_TDATA,
        oupstream_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   inpstream_TVALID;
input   oupstream_TREADY;
input  [63:0] inpstream_TDATA;
output   inpstream_TREADY;
output  [63:0] oupstream_TDATA;
output   oupstream_TVALID;

reg ap_idle;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln9_fu_73_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] or_ln13_reg_136;
wire    regslice_both_oupstream_U_apdone_blk;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
reg   [0:0] or_ln13_reg_136_pp0_iter1_reg;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    inpstream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    oupstream_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [63:0] inpstream_read_reg_131;
wire   [0:0] or_ln13_fu_103_p2;
reg   [13:0] v_fu_48;
wire   [13:0] v_3_fu_109_p2;
wire    ap_loop_init;
reg   [13:0] ap_sig_allocacmp_v_2;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln13_fu_79_p2;
wire   [0:0] icmp_ln13_1_fu_85_p2;
wire   [0:0] and_ln13_fu_91_p2;
wire   [0:0] icmp_ln13_2_fu_97_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    regslice_both_inpstream_U_apdone_blk;
wire   [63:0] inpstream_TDATA_int_regslice;
wire    inpstream_TVALID_int_regslice;
reg    inpstream_TREADY_int_regslice;
wire    regslice_both_inpstream_U_ack_in;
reg    oupstream_TVALID_int_regslice;
wire    oupstream_TREADY_int_regslice;
wire    regslice_both_oupstream_U_vld_out;
reg    ap_condition_122;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cyclicPrefixRemoval_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

cyclicPrefixRemoval_regslice_both #(
    .DataWidth( 64 ))
regslice_both_inpstream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inpstream_TDATA),
    .vld_in(inpstream_TVALID),
    .ack_in(regslice_both_inpstream_U_ack_in),
    .data_out(inpstream_TDATA_int_regslice),
    .vld_out(inpstream_TVALID_int_regslice),
    .ack_out(inpstream_TREADY_int_regslice),
    .apdone_blk(regslice_both_inpstream_U_apdone_blk)
);

cyclicPrefixRemoval_regslice_both #(
    .DataWidth( 64 ))
regslice_both_oupstream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inpstream_read_reg_131),
    .vld_in(oupstream_TVALID_int_regslice),
    .ack_in(oupstream_TREADY_int_regslice),
    .data_out(oupstream_TDATA),
    .vld_out(regslice_both_oupstream_U_vld_out),
    .ack_out(oupstream_TREADY),
    .apdone_blk(regslice_both_oupstream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_122)) begin
        if ((icmp_ln9_fu_73_p2 == 1'd0)) begin
            v_fu_48 <= v_3_fu_109_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            v_fu_48 <= 14'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        or_ln13_reg_136_pp0_iter1_reg <= or_ln13_reg_136;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln9_fu_73_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inpstream_read_reg_131 <= inpstream_TDATA_int_regslice;
        or_ln13_reg_136 <= or_ln13_fu_103_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln9_fu_73_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_v_2 = 14'd1;
    end else begin
        ap_sig_allocacmp_v_2 = v_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln9_fu_73_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inpstream_TDATA_blk_n = inpstream_TVALID_int_regslice;
    end else begin
        inpstream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln9_fu_73_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inpstream_TREADY_int_regslice = 1'b1;
    end else begin
        inpstream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (or_ln13_reg_136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (or_ln13_reg_136 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        oupstream_TDATA_blk_n = oupstream_TREADY_int_regslice;
    end else begin
        oupstream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_ln13_reg_136 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        oupstream_TVALID_int_regslice = 1'b1;
    end else begin
        oupstream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln13_fu_91_p2 = (icmp_ln13_fu_79_p2 & icmp_ln13_1_fu_85_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_oupstream_U_apdone_blk == 1'b1)) | ((or_ln13_reg_136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (oupstream_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_oupstream_U_apdone_blk == 1'b1) | ((or_ln13_reg_136 == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0)))) | ((icmp_ln9_fu_73_p2 == 1'd0) & (ap_start_int == 1'b1) & (inpstream_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_oupstream_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((or_ln13_reg_136_pp0_iter1_reg == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_oupstream_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state2_io) | ((or_ln13_reg_136 == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0)))) | ((icmp_ln9_fu_73_p2 == 1'd0) & (ap_start_int == 1'b1) & (inpstream_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_oupstream_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((or_ln13_reg_136_pp0_iter1_reg == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_oupstream_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state2_io) | ((or_ln13_reg_136 == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0)))) | ((icmp_ln9_fu_73_p2 == 1'd0) & (ap_start_int == 1'b1) & (inpstream_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln9_fu_73_p2 == 1'd0) & (inpstream_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((or_ln13_reg_136 == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((regslice_both_oupstream_U_apdone_blk == 1'b1) | ((or_ln13_reg_136 == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state3_io = ((or_ln13_reg_136_pp0_iter1_reg == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((or_ln13_reg_136_pp0_iter1_reg == 1'd1) & (oupstream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_condition_122 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign icmp_ln13_1_fu_85_p2 = ((ap_sig_allocacmp_v_2 < 14'd4417) ? 1'b1 : 1'b0);

assign icmp_ln13_2_fu_97_p2 = ((ap_sig_allocacmp_v_2 > 14'd4704) ? 1'b1 : 1'b0);

assign icmp_ln13_fu_79_p2 = ((ap_sig_allocacmp_v_2 > 14'd320) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_73_p2 = ((ap_sig_allocacmp_v_2 == 14'd8801) ? 1'b1 : 1'b0);

assign inpstream_TREADY = regslice_both_inpstream_U_ack_in;

assign or_ln13_fu_103_p2 = (icmp_ln13_2_fu_97_p2 | and_ln13_fu_91_p2);

assign oupstream_TVALID = regslice_both_oupstream_U_vld_out;

assign v_3_fu_109_p2 = (ap_sig_allocacmp_v_2 + 14'd1);

endmodule //cyclicPrefixRemoval
