sudo: false
language: cpp

#cache:
# ccache: false
# directories:
#  - ~/.local-bin


env:
  global:
    - MAKEFLAGS="-j 2"

include:
  # Latest gcc supported on Travis Linux
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-9
          - gperf
          - build-essential
          - bison
          - flex
          - libreadline-dev
          - gawk
          - tcl-dev
          - libffi-dev
          - git
          - graphviz
          - xdot
          - pkg-config
          - python
          - python3
          - libboost-system-dev
          - libboost-python-dev
          - libboost-filesystem-dev
          - zlib1g-dev
    env:
      - MATRIX_EVAL="CONFIG=gcc && CC=gcc-9 && CXX=g++-9"

before_install:
  - ./.travis/setup.sh

script:
  - ./.travis/build-and-test.sh

