// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module crc24a_crc24a_Pipeline_VITIS_LOOP_60_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_V_address0,
        p_V_ce0,
        p_V_we0,
        p_V_d0,
        startIdx_reload,
        dividend_V_97_reload,
        dividend_V_98_reload,
        dividend_V_99_reload,
        dividend_V_100_reload,
        dividend_V_101_reload,
        dividend_V_102_reload,
        dividend_V_103_reload,
        dividend_V_104_reload,
        dividend_V_105_reload,
        dividend_V_106_reload,
        dividend_V_107_reload,
        dividend_V_108_reload,
        dividend_V_109_reload,
        dividend_V_110_reload,
        dividend_V_111_reload,
        dividend_V_112_reload,
        dividend_V_113_reload,
        dividend_V_114_reload,
        dividend_V_115_reload,
        dividend_V_116_reload,
        dividend_V_117_reload,
        dividend_V_118_reload,
        dividend_V_119_reload,
        dividend_V_120_reload,
        dividend_V_121_reload,
        dividend_V_122_reload,
        dividend_V_123_reload,
        dividend_V_124_reload,
        dividend_V_125_reload,
        dividend_V_126_reload,
        dividend_V_127_reload,
        dividend_V_128_reload,
        dividend_V_129_reload,
        dividend_V_130_reload,
        dividend_V_131_reload,
        dividend_V_132_reload,
        dividend_V_133_reload,
        dividend_V_134_reload,
        dividend_V_135_reload,
        dividend_V_136_reload,
        dividend_V_137_reload,
        dividend_V_138_reload,
        dividend_V_139_reload,
        dividend_V_140_reload,
        dividend_V_141_reload,
        dividend_V_142_reload,
        dividend_V_143_reload,
        dividend_V_144_reload
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] p_V_address0;
output   p_V_ce0;
output   p_V_we0;
output  [0:0] p_V_d0;
input  [5:0] startIdx_reload;
input  [0:0] dividend_V_97_reload;
input  [0:0] dividend_V_98_reload;
input  [0:0] dividend_V_99_reload;
input  [0:0] dividend_V_100_reload;
input  [0:0] dividend_V_101_reload;
input  [0:0] dividend_V_102_reload;
input  [0:0] dividend_V_103_reload;
input  [0:0] dividend_V_104_reload;
input  [0:0] dividend_V_105_reload;
input  [0:0] dividend_V_106_reload;
input  [0:0] dividend_V_107_reload;
input  [0:0] dividend_V_108_reload;
input  [0:0] dividend_V_109_reload;
input  [0:0] dividend_V_110_reload;
input  [0:0] dividend_V_111_reload;
input  [0:0] dividend_V_112_reload;
input  [0:0] dividend_V_113_reload;
input  [0:0] dividend_V_114_reload;
input  [0:0] dividend_V_115_reload;
input  [0:0] dividend_V_116_reload;
input  [0:0] dividend_V_117_reload;
input  [0:0] dividend_V_118_reload;
input  [0:0] dividend_V_119_reload;
input  [0:0] dividend_V_120_reload;
input  [0:0] dividend_V_121_reload;
input  [0:0] dividend_V_122_reload;
input  [0:0] dividend_V_123_reload;
input  [0:0] dividend_V_124_reload;
input  [0:0] dividend_V_125_reload;
input  [0:0] dividend_V_126_reload;
input  [0:0] dividend_V_127_reload;
input  [0:0] dividend_V_128_reload;
input  [0:0] dividend_V_129_reload;
input  [0:0] dividend_V_130_reload;
input  [0:0] dividend_V_131_reload;
input  [0:0] dividend_V_132_reload;
input  [0:0] dividend_V_133_reload;
input  [0:0] dividend_V_134_reload;
input  [0:0] dividend_V_135_reload;
input  [0:0] dividend_V_136_reload;
input  [0:0] dividend_V_137_reload;
input  [0:0] dividend_V_138_reload;
input  [0:0] dividend_V_139_reload;
input  [0:0] dividend_V_140_reload;
input  [0:0] dividend_V_141_reload;
input  [0:0] dividend_V_142_reload;
input  [0:0] dividend_V_143_reload;
input  [0:0] dividend_V_144_reload;

reg ap_idle;
reg p_V_ce0;
reg p_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln60_fu_449_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] i_1_reg_589;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_3_fu_471_p50;
reg   [0:0] tmp_3_reg_597;
wire   [63:0] zext_ln60_fu_578_p1;
wire    ap_block_pp0_stage0;
reg   [4:0] i_fu_130;
wire   [4:0] add_ln60_fu_455_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_1;
wire   [5:0] zext_ln62_fu_461_p1;
wire   [5:0] tmp_3_fu_471_p49;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

crc24a_mux_486_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 1 ),
    .din18_WIDTH( 1 ),
    .din19_WIDTH( 1 ),
    .din20_WIDTH( 1 ),
    .din21_WIDTH( 1 ),
    .din22_WIDTH( 1 ),
    .din23_WIDTH( 1 ),
    .din24_WIDTH( 1 ),
    .din25_WIDTH( 1 ),
    .din26_WIDTH( 1 ),
    .din27_WIDTH( 1 ),
    .din28_WIDTH( 1 ),
    .din29_WIDTH( 1 ),
    .din30_WIDTH( 1 ),
    .din31_WIDTH( 1 ),
    .din32_WIDTH( 1 ),
    .din33_WIDTH( 1 ),
    .din34_WIDTH( 1 ),
    .din35_WIDTH( 1 ),
    .din36_WIDTH( 1 ),
    .din37_WIDTH( 1 ),
    .din38_WIDTH( 1 ),
    .din39_WIDTH( 1 ),
    .din40_WIDTH( 1 ),
    .din41_WIDTH( 1 ),
    .din42_WIDTH( 1 ),
    .din43_WIDTH( 1 ),
    .din44_WIDTH( 1 ),
    .din45_WIDTH( 1 ),
    .din46_WIDTH( 1 ),
    .din47_WIDTH( 1 ),
    .din48_WIDTH( 6 ),
    .dout_WIDTH( 1 ))
mux_486_1_1_1_U199(
    .din0(dividend_V_97_reload),
    .din1(dividend_V_98_reload),
    .din2(dividend_V_99_reload),
    .din3(dividend_V_100_reload),
    .din4(dividend_V_101_reload),
    .din5(dividend_V_102_reload),
    .din6(dividend_V_103_reload),
    .din7(dividend_V_104_reload),
    .din8(dividend_V_105_reload),
    .din9(dividend_V_106_reload),
    .din10(dividend_V_107_reload),
    .din11(dividend_V_108_reload),
    .din12(dividend_V_109_reload),
    .din13(dividend_V_110_reload),
    .din14(dividend_V_111_reload),
    .din15(dividend_V_112_reload),
    .din16(dividend_V_113_reload),
    .din17(dividend_V_114_reload),
    .din18(dividend_V_115_reload),
    .din19(dividend_V_116_reload),
    .din20(dividend_V_117_reload),
    .din21(dividend_V_118_reload),
    .din22(dividend_V_119_reload),
    .din23(dividend_V_120_reload),
    .din24(dividend_V_121_reload),
    .din25(dividend_V_122_reload),
    .din26(dividend_V_123_reload),
    .din27(dividend_V_124_reload),
    .din28(dividend_V_125_reload),
    .din29(dividend_V_126_reload),
    .din30(dividend_V_127_reload),
    .din31(dividend_V_128_reload),
    .din32(dividend_V_129_reload),
    .din33(dividend_V_130_reload),
    .din34(dividend_V_131_reload),
    .din35(dividend_V_132_reload),
    .din36(dividend_V_133_reload),
    .din37(dividend_V_134_reload),
    .din38(dividend_V_135_reload),
    .din39(dividend_V_136_reload),
    .din40(dividend_V_137_reload),
    .din41(dividend_V_138_reload),
    .din42(dividend_V_139_reload),
    .din43(dividend_V_140_reload),
    .din44(dividend_V_141_reload),
    .din45(dividend_V_142_reload),
    .din46(dividend_V_143_reload),
    .din47(dividend_V_144_reload),
    .din48(tmp_3_fu_471_p49),
    .dout(tmp_3_fu_471_p50)
);

crc24a_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln60_fu_449_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_130 <= add_ln60_fu_455_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_130 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_589 <= ap_sig_allocacmp_i_1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln60_fu_449_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_3_reg_597 <= tmp_3_fu_471_p50;
    end
end

always @ (*) begin
    if (((icmp_ln60_fu_449_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_130;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_V_ce0 = 1'b1;
    end else begin
        p_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_V_we0 = 1'b1;
    end else begin
        p_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln60_fu_455_p2 = (ap_sig_allocacmp_i_1 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln60_fu_449_p2 = ((ap_sig_allocacmp_i_1 == 5'd24) ? 1'b1 : 1'b0);

assign p_V_address0 = zext_ln60_fu_578_p1;

assign p_V_d0 = tmp_3_reg_597;

assign tmp_3_fu_471_p49 = (zext_ln62_fu_461_p1 + startIdx_reload);

assign zext_ln60_fu_578_p1 = i_1_reg_589;

assign zext_ln62_fu_461_p1 = ap_sig_allocacmp_i_1;

endmodule //crc24a_crc24a_Pipeline_VITIS_LOOP_60_6
