#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("index", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("output_V_data_0_V_din", 8, hls_out, 1, "ap_fifo", "fifo_data", 1),
	Port_Property("output_V_data_0_V_full_n", 1, hls_in, 1, "ap_fifo", "fifo_status", 1),
	Port_Property("output_V_data_0_V_write", 1, hls_out, 1, "ap_fifo", "fifo_update", 1),
	Port_Property("output_V_data_1_V_din", 8, hls_out, 2, "ap_fifo", "fifo_data", 1),
	Port_Property("output_V_data_1_V_full_n", 1, hls_in, 2, "ap_fifo", "fifo_status", 1),
	Port_Property("output_V_data_1_V_write", 1, hls_out, 2, "ap_fifo", "fifo_update", 1),
	Port_Property("output_V_data_2_V_din", 8, hls_out, 3, "ap_fifo", "fifo_data", 1),
	Port_Property("output_V_data_2_V_full_n", 1, hls_in, 3, "ap_fifo", "fifo_status", 1),
	Port_Property("output_V_data_2_V_write", 1, hls_out, 3, "ap_fifo", "fifo_update", 1),
	Port_Property("output_V_data_3_V_din", 8, hls_out, 4, "ap_fifo", "fifo_data", 1),
	Port_Property("output_V_data_3_V_full_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 1),
	Port_Property("output_V_data_3_V_write", 1, hls_out, 4, "ap_fifo", "fifo_update", 1),
	Port_Property("output_V_data_4_V_din", 8, hls_out, 5, "ap_fifo", "fifo_data", 1),
	Port_Property("output_V_data_4_V_full_n", 1, hls_in, 5, "ap_fifo", "fifo_status", 1),
	Port_Property("output_V_data_4_V_write", 1, hls_out, 5, "ap_fifo", "fifo_update", 1),
	Port_Property("output_V_data_5_V_din", 8, hls_out, 6, "ap_fifo", "fifo_data", 1),
	Port_Property("output_V_data_5_V_full_n", 1, hls_in, 6, "ap_fifo", "fifo_status", 1),
	Port_Property("output_V_data_5_V_write", 1, hls_out, 6, "ap_fifo", "fifo_update", 1),
	Port_Property("output_V_data_6_V_din", 8, hls_out, 7, "ap_fifo", "fifo_data", 1),
	Port_Property("output_V_data_6_V_full_n", 1, hls_in, 7, "ap_fifo", "fifo_status", 1),
	Port_Property("output_V_data_6_V_write", 1, hls_out, 7, "ap_fifo", "fifo_update", 1),
	Port_Property("output_V_data_7_V_din", 8, hls_out, 8, "ap_fifo", "fifo_data", 1),
	Port_Property("output_V_data_7_V_full_n", 1, hls_in, 8, "ap_fifo", "fifo_status", 1),
	Port_Property("output_V_data_7_V_write", 1, hls_out, 8, "ap_fifo", "fifo_update", 1),
};
const char* HLS_Design_Meta::dut_name = "a5a";
