-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
-- Version: 2022.2.2
-- Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity crc24a_crc24a_Pipeline_loop2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    crc_V_85 : IN STD_LOGIC_VECTOR (0 downto 0);
    crc_V_84 : IN STD_LOGIC_VECTOR (0 downto 0);
    crc_V_83 : IN STD_LOGIC_VECTOR (0 downto 0);
    crc_V_82 : IN STD_LOGIC_VECTOR (0 downto 0);
    crc_V_81 : IN STD_LOGIC_VECTOR (0 downto 0);
    crc_V_80 : IN STD_LOGIC_VECTOR (0 downto 0);
    crc_V_79 : IN STD_LOGIC_VECTOR (0 downto 0);
    crc_V_78 : IN STD_LOGIC_VECTOR (0 downto 0);
    tmp_last_V : IN STD_LOGIC_VECTOR (0 downto 0);
    crc_V_31_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_31_out_ap_vld : OUT STD_LOGIC;
    crc_V_98_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_98_out_ap_vld : OUT STD_LOGIC;
    crc_V_97_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_97_out_ap_vld : OUT STD_LOGIC;
    crc_V_28_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_28_out_ap_vld : OUT STD_LOGIC;
    crc_V_96_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_96_out_ap_vld : OUT STD_LOGIC;
    crc_V_95_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_95_out_ap_vld : OUT STD_LOGIC;
    crc_V_94_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_94_out_ap_vld : OUT STD_LOGIC;
    crc_V_93_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_93_out_ap_vld : OUT STD_LOGIC;
    crc_V_92_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_92_out_ap_vld : OUT STD_LOGIC;
    crc_V_22_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_22_out_ap_vld : OUT STD_LOGIC;
    crc_V_21_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_21_out_ap_vld : OUT STD_LOGIC;
    crc_V_91_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_91_out_ap_vld : OUT STD_LOGIC;
    crc_V_90_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_90_out_ap_vld : OUT STD_LOGIC;
    crc_V_18_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_18_out_ap_vld : OUT STD_LOGIC;
    crc_V_17_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_17_out_ap_vld : OUT STD_LOGIC;
    crc_V_89_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_89_out_ap_vld : OUT STD_LOGIC;
    crc_V_15_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_15_out_ap_vld : OUT STD_LOGIC;
    crc_V_14_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_14_out_ap_vld : OUT STD_LOGIC;
    crc_V_88_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_88_out_ap_vld : OUT STD_LOGIC;
    crc_V_87_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_87_out_ap_vld : OUT STD_LOGIC;
    crc_V_11_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_11_out_ap_vld : OUT STD_LOGIC;
    crc_V_10_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_10_out_ap_vld : OUT STD_LOGIC;
    crc_V_9_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_9_out_ap_vld : OUT STD_LOGIC;
    crc_V_8_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_8_out_ap_vld : OUT STD_LOGIC;
    crc_V_86_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_86_out_ap_vld : OUT STD_LOGIC;
    crc_V_6_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_6_out_ap_vld : OUT STD_LOGIC;
    crc_V_5_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_5_out_ap_vld : OUT STD_LOGIC;
    crc_V_4_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_4_out_ap_vld : OUT STD_LOGIC;
    crc_V_3_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_3_out_ap_vld : OUT STD_LOGIC;
    crc_V_2_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_2_out_ap_vld : OUT STD_LOGIC;
    crc_V_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_1_out_ap_vld : OUT STD_LOGIC;
    crc_V_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    crc_V_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of crc24a_crc24a_Pipeline_loop2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln21_fu_770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal crc_V_31_reg_410 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_90_reg_421 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_89_reg_432 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_28_reg_443 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_88_reg_454 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_87_reg_465 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_86_reg_476 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_77_reg_487 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_76_reg_498 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_22_reg_509 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_21_reg_520 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_75_reg_531 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_74_reg_542 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_18_reg_553 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_17_reg_564 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_73_reg_575 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_15_reg_586 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_14_reg_597 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_72_reg_608 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_71_reg_619 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_11_reg_630 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_10_reg_641 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_9_reg_652 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_8_reg_663 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_70_reg_674 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_6_reg_685 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_5_reg_696 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_4_reg_707 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_3_reg_718 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_2_reg_729 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_1_reg_740 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_reg_751 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_69_fu_1018_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_38_fu_1042_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_68_fu_1062_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_67_fu_1082_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_66_fu_1130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_65_fu_1172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_64_fu_1214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_63_fu_1232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_62_fu_1276_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_61_fu_1310_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_60_fu_1366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_59_fu_1414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_58_fu_1434_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_57_fu_1448_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_56_fu_1504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_55_fu_1518_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_54_fu_1534_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_53_fu_1578_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_52_fu_1608_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_51_fu_1622_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_50_fu_1644_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_49_fu_1660_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_48_fu_1676_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_47_fu_1714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_46_fu_1740_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_45_fu_1770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_44_fu_1788_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_43_fu_1808_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_42_fu_1828_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_41_fu_1848_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_40_fu_1868_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_V_39_fu_1882_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_31_phi_fu_413_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_phi_mux_crc_V_90_phi_fu_424_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_89_phi_fu_435_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_28_phi_fu_446_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_88_phi_fu_457_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_87_phi_fu_468_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_86_phi_fu_479_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_77_phi_fu_490_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_76_phi_fu_501_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_22_phi_fu_512_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_21_phi_fu_523_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_75_phi_fu_534_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_74_phi_fu_545_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_18_phi_fu_556_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_17_phi_fu_567_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_73_phi_fu_578_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_15_phi_fu_589_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_14_phi_fu_600_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_72_phi_fu_611_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_71_phi_fu_622_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_11_phi_fu_633_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_10_phi_fu_644_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_9_phi_fu_655_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_8_phi_fu_666_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_70_phi_fu_677_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_6_phi_fu_688_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_5_phi_fu_699_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_4_phi_fu_710_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_3_phi_fu_721_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_2_phi_fu_732_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_1_phi_fu_743_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_crc_V_phi_fu_754_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_fu_128 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln21_fu_776_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln1019_fu_782_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal lhs_V_fu_786_p10 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln23_fu_808_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_fu_922_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln23_fu_964_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_fu_970_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_1_fu_928_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_1_fu_976_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_2_fu_934_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_2_fu_982_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_3_fu_940_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_4_fu_946_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_5_fu_952_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_4_fu_994_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_3_fu_988_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_5_fu_1000_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_6_fu_958_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_6_fu_1006_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_fu_1012_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_fu_1030_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_2_fu_1024_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_7_fu_1036_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_1_fu_1048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_5_fu_916_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_fu_1054_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_8_fu_1070_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_4_fu_1076_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_9_fu_1088_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_2_fu_1100_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_6_fu_1094_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_3_fu_1106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_11_fu_1118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_10_fu_1112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_12_fu_1124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_13_fu_1136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_8_fu_1142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_4_fu_1148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_15_fu_1160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_14_fu_1154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_16_fu_1166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_17_fu_1178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_10_fu_1184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_5_fu_1190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_19_fu_1202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_18_fu_1196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_20_fu_1208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_7_fu_1220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_6_fu_1226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_7_fu_1238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_21_fu_1244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_22_fu_1250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_23_fu_1256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_4_fu_850_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_24_fu_1262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_2_fu_1268_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1499_10_fu_874_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_25_fu_1284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_26_fu_1290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_27_fu_1304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_4_fu_1296_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_28_fu_1318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_29_fu_1324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_13_fu_1330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_30_fu_1336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_32_fu_1348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_33_fu_1354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_31_fu_1342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_34_fu_1360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_35_fu_1372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_36_fu_1378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_15_fu_1384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_37_fu_1390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_39_fu_1402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_38_fu_1396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_40_fu_1408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_3_fu_844_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_41_fu_1428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_6_fu_1420_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_42_fu_1442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1499_4_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_43_fu_1456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_45_fu_1468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_44_fu_1462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_46_fu_1474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_17_fu_1480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_48_fu_1492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_47_fu_1486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_49_fu_1498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_2_fu_898_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_9_fu_1510_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1499_9_fu_868_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_11_fu_1526_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_50_fu_1542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_51_fu_1548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_52_fu_1554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_19_fu_1560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_53_fu_1566_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_54_fu_1572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_55_fu_1584_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_21_fu_1590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_56_fu_1596_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_57_fu_1602_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_1_fu_892_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_13_fu_1614_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1499_8_fu_862_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_58_fu_1630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_15_fu_1636_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1499_3_fu_832_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_17_fu_1652_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1499_12_fu_886_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_19_fu_1668_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_59_fu_1684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_60_fu_1690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_23_fu_1696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_61_fu_1702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_62_fu_1708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_63_fu_1720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_fu_826_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_8_fu_1726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_21_fu_1732_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1499_1_fu_820_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_23_fu_1748_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_24_fu_1756_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_25_fu_1764_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_26_fu_1776_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1499_16_fu_910_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_10_fu_1782_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_27_fu_1796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1499_15_fu_904_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_11_fu_1802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_28_fu_1816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1499_11_fu_880_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_12_fu_1822_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_29_fu_1836_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1499_7_fu_856_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_13_fu_1842_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_30_fu_1856_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1499_fu_814_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln27_14_fu_1862_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_31_fu_1876_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component crc24a_mux_83_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component crc24a_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_83_1_1_1_U1 : component crc24a_mux_83_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 1,
        din5_WIDTH => 1,
        din6_WIDTH => 1,
        din7_WIDTH => 1,
        din8_WIDTH => 3,
        dout_WIDTH => 1)
    port map (
        din0 => ap_phi_mux_crc_V_phi_fu_754_p4,
        din1 => ap_phi_mux_crc_V_1_phi_fu_743_p4,
        din2 => ap_phi_mux_crc_V_2_phi_fu_732_p4,
        din3 => ap_phi_mux_crc_V_3_phi_fu_721_p4,
        din4 => ap_phi_mux_crc_V_4_phi_fu_710_p4,
        din5 => ap_phi_mux_crc_V_5_phi_fu_699_p4,
        din6 => ap_phi_mux_crc_V_6_phi_fu_688_p4,
        din7 => ap_phi_mux_crc_V_70_phi_fu_677_p4,
        din8 => trunc_ln1019_fu_782_p1,
        dout => lhs_V_fu_786_p10);

    flow_control_loop_pipe_sequential_init_U : component crc24a_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    k_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
                if ((icmp_ln21_fu_770_p2 = ap_const_lv1_0)) then 
                    k_fu_128 <= add_ln21_fu_776_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_128 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln21_fu_770_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
                crc_V_10_reg_641 <= crc_V_49_fu_1660_p3;
                crc_V_11_reg_630 <= crc_V_50_fu_1644_p3;
                crc_V_14_reg_597 <= crc_V_53_fu_1578_p2;
                crc_V_15_reg_586 <= crc_V_54_fu_1534_p3;
                crc_V_17_reg_564 <= crc_V_56_fu_1504_p2;
                crc_V_18_reg_553 <= crc_V_57_fu_1448_p3;
                crc_V_1_reg_740 <= crc_V_40_fu_1868_p3;
                crc_V_21_reg_520 <= crc_V_60_fu_1366_p2;
                crc_V_22_reg_509 <= crc_V_61_fu_1310_p3;
                crc_V_28_reg_443 <= crc_V_67_fu_1082_p2;
                crc_V_2_reg_729 <= crc_V_41_fu_1848_p3;
                crc_V_31_reg_410 <= crc_V_69_fu_1018_p2;
                crc_V_3_reg_718 <= crc_V_42_fu_1828_p3;
                crc_V_4_reg_707 <= crc_V_43_fu_1808_p3;
                crc_V_5_reg_696 <= crc_V_44_fu_1788_p3;
                crc_V_6_reg_685 <= crc_V_45_fu_1770_p2;
                crc_V_70_reg_674 <= crc_V_46_fu_1740_p3;
                crc_V_71_reg_619 <= crc_V_51_fu_1622_p3;
                crc_V_72_reg_608 <= crc_V_52_fu_1608_p2;
                crc_V_73_reg_575 <= crc_V_55_fu_1518_p3;
                crc_V_74_reg_542 <= crc_V_58_fu_1434_p3;
                crc_V_75_reg_531 <= crc_V_59_fu_1414_p2;
                crc_V_76_reg_498 <= crc_V_62_fu_1276_p3;
                crc_V_77_reg_487 <= crc_V_63_fu_1232_p2;
                crc_V_86_reg_476 <= crc_V_64_fu_1214_p2;
                crc_V_87_reg_465 <= crc_V_65_fu_1172_p2;
                crc_V_88_reg_454 <= crc_V_66_fu_1130_p2;
                crc_V_89_reg_432 <= crc_V_68_fu_1062_p3;
                crc_V_8_reg_663 <= crc_V_47_fu_1714_p2;
                crc_V_90_reg_421 <= crc_V_38_fu_1042_p2;
                crc_V_9_reg_652 <= crc_V_48_fu_1676_p3;
                crc_V_reg_751 <= crc_V_39_fu_1882_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln21_fu_776_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv4_1));
    and_ln23_fu_808_p2 <= (tmp_last_V and lhs_V_fu_786_p10);
    and_ln27_10_fu_1782_p2 <= (xor_ln27_26_fu_1776_p2 and ap_phi_mux_crc_V_5_phi_fu_699_p4);
    and_ln27_11_fu_1802_p2 <= (xor_ln27_27_fu_1796_p2 and ap_phi_mux_crc_V_4_phi_fu_710_p4);
    and_ln27_12_fu_1822_p2 <= (xor_ln27_28_fu_1816_p2 and ap_phi_mux_crc_V_3_phi_fu_721_p4);
    and_ln27_13_fu_1842_p2 <= (xor_ln27_29_fu_1836_p2 and ap_phi_mux_crc_V_2_phi_fu_732_p4);
    and_ln27_14_fu_1862_p2 <= (xor_ln27_30_fu_1856_p2 and ap_phi_mux_crc_V_1_phi_fu_743_p4);
    and_ln27_1_fu_1048_p2 <= (icmp_ln27_5_fu_952_p2 and and_ln23_fu_808_p2);
    and_ln27_2_fu_1100_p2 <= (icmp_ln27_4_fu_946_p2 and and_ln23_fu_808_p2);
    and_ln27_3_fu_1106_p2 <= (icmp_ln27_3_fu_940_p2 and and_ln23_fu_808_p2);
    and_ln27_4_fu_1148_p2 <= (icmp_ln27_2_fu_934_p2 and and_ln23_fu_808_p2);
    and_ln27_5_fu_1190_p2 <= (icmp_ln27_1_fu_928_p2 and and_ln23_fu_808_p2);
    and_ln27_6_fu_1226_p2 <= (icmp_ln27_7_fu_1220_p2 and and_ln23_fu_808_p2);
    and_ln27_7_fu_1238_p2 <= (icmp_ln27_fu_922_p2 and and_ln23_fu_808_p2);
    and_ln27_8_fu_1726_p2 <= (or_ln27_63_fu_1720_p2 and ap_phi_mux_crc_V_70_phi_fu_677_p4);
    and_ln27_fu_1030_p2 <= (icmp_ln27_6_fu_958_p2 and and_ln23_fu_808_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_crc_V_10_phi_fu_644_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_10_reg_641, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_10_phi_fu_644_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_10_phi_fu_644_p4 <= crc_V_10_reg_641;
        end if; 
    end process;


    ap_phi_mux_crc_V_11_phi_fu_633_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_11_reg_630, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_11_phi_fu_633_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_11_phi_fu_633_p4 <= crc_V_11_reg_630;
        end if; 
    end process;


    ap_phi_mux_crc_V_14_phi_fu_600_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_14_reg_597, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_14_phi_fu_600_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_14_phi_fu_600_p4 <= crc_V_14_reg_597;
        end if; 
    end process;


    ap_phi_mux_crc_V_15_phi_fu_589_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_15_reg_586, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_15_phi_fu_589_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_15_phi_fu_589_p4 <= crc_V_15_reg_586;
        end if; 
    end process;


    ap_phi_mux_crc_V_17_phi_fu_567_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_17_reg_564, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_17_phi_fu_567_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_17_phi_fu_567_p4 <= crc_V_17_reg_564;
        end if; 
    end process;


    ap_phi_mux_crc_V_18_phi_fu_556_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_18_reg_553, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_18_phi_fu_556_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_18_phi_fu_556_p4 <= crc_V_18_reg_553;
        end if; 
    end process;


    ap_phi_mux_crc_V_1_phi_fu_743_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_79, crc_V_1_reg_740, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_1_phi_fu_743_p4 <= crc_V_79;
        else 
            ap_phi_mux_crc_V_1_phi_fu_743_p4 <= crc_V_1_reg_740;
        end if; 
    end process;


    ap_phi_mux_crc_V_21_phi_fu_523_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_21_reg_520, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_21_phi_fu_523_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_21_phi_fu_523_p4 <= crc_V_21_reg_520;
        end if; 
    end process;


    ap_phi_mux_crc_V_22_phi_fu_512_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_22_reg_509, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_22_phi_fu_512_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_22_phi_fu_512_p4 <= crc_V_22_reg_509;
        end if; 
    end process;


    ap_phi_mux_crc_V_28_phi_fu_446_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_28_reg_443, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_28_phi_fu_446_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_28_phi_fu_446_p4 <= crc_V_28_reg_443;
        end if; 
    end process;


    ap_phi_mux_crc_V_2_phi_fu_732_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_80, crc_V_2_reg_729, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_2_phi_fu_732_p4 <= crc_V_80;
        else 
            ap_phi_mux_crc_V_2_phi_fu_732_p4 <= crc_V_2_reg_729;
        end if; 
    end process;


    ap_phi_mux_crc_V_31_phi_fu_413_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_31_reg_410, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_31_phi_fu_413_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_31_phi_fu_413_p4 <= crc_V_31_reg_410;
        end if; 
    end process;


    ap_phi_mux_crc_V_3_phi_fu_721_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_81, crc_V_3_reg_718, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_3_phi_fu_721_p4 <= crc_V_81;
        else 
            ap_phi_mux_crc_V_3_phi_fu_721_p4 <= crc_V_3_reg_718;
        end if; 
    end process;


    ap_phi_mux_crc_V_4_phi_fu_710_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_82, crc_V_4_reg_707, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_4_phi_fu_710_p4 <= crc_V_82;
        else 
            ap_phi_mux_crc_V_4_phi_fu_710_p4 <= crc_V_4_reg_707;
        end if; 
    end process;


    ap_phi_mux_crc_V_5_phi_fu_699_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_83, crc_V_5_reg_696, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_5_phi_fu_699_p4 <= crc_V_83;
        else 
            ap_phi_mux_crc_V_5_phi_fu_699_p4 <= crc_V_5_reg_696;
        end if; 
    end process;


    ap_phi_mux_crc_V_6_phi_fu_688_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_84, crc_V_6_reg_685, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_6_phi_fu_688_p4 <= crc_V_84;
        else 
            ap_phi_mux_crc_V_6_phi_fu_688_p4 <= crc_V_6_reg_685;
        end if; 
    end process;


    ap_phi_mux_crc_V_70_phi_fu_677_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_85, crc_V_70_reg_674, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_70_phi_fu_677_p4 <= crc_V_85;
        else 
            ap_phi_mux_crc_V_70_phi_fu_677_p4 <= crc_V_70_reg_674;
        end if; 
    end process;


    ap_phi_mux_crc_V_71_phi_fu_622_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_71_reg_619, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_71_phi_fu_622_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_71_phi_fu_622_p4 <= crc_V_71_reg_619;
        end if; 
    end process;


    ap_phi_mux_crc_V_72_phi_fu_611_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_72_reg_608, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_72_phi_fu_611_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_72_phi_fu_611_p4 <= crc_V_72_reg_608;
        end if; 
    end process;


    ap_phi_mux_crc_V_73_phi_fu_578_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_73_reg_575, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_73_phi_fu_578_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_73_phi_fu_578_p4 <= crc_V_73_reg_575;
        end if; 
    end process;


    ap_phi_mux_crc_V_74_phi_fu_545_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_74_reg_542, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_74_phi_fu_545_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_74_phi_fu_545_p4 <= crc_V_74_reg_542;
        end if; 
    end process;


    ap_phi_mux_crc_V_75_phi_fu_534_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_75_reg_531, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_75_phi_fu_534_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_75_phi_fu_534_p4 <= crc_V_75_reg_531;
        end if; 
    end process;


    ap_phi_mux_crc_V_76_phi_fu_501_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_76_reg_498, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_76_phi_fu_501_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_76_phi_fu_501_p4 <= crc_V_76_reg_498;
        end if; 
    end process;


    ap_phi_mux_crc_V_77_phi_fu_490_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_77_reg_487, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_77_phi_fu_490_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_77_phi_fu_490_p4 <= crc_V_77_reg_487;
        end if; 
    end process;


    ap_phi_mux_crc_V_86_phi_fu_479_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_86_reg_476, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_86_phi_fu_479_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_86_phi_fu_479_p4 <= crc_V_86_reg_476;
        end if; 
    end process;


    ap_phi_mux_crc_V_87_phi_fu_468_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_87_reg_465, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_87_phi_fu_468_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_87_phi_fu_468_p4 <= crc_V_87_reg_465;
        end if; 
    end process;


    ap_phi_mux_crc_V_88_phi_fu_457_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_88_reg_454, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_88_phi_fu_457_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_88_phi_fu_457_p4 <= crc_V_88_reg_454;
        end if; 
    end process;


    ap_phi_mux_crc_V_89_phi_fu_435_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_89_reg_432, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_89_phi_fu_435_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_89_phi_fu_435_p4 <= crc_V_89_reg_432;
        end if; 
    end process;


    ap_phi_mux_crc_V_8_phi_fu_666_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_8_reg_663, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_8_phi_fu_666_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_8_phi_fu_666_p4 <= crc_V_8_reg_663;
        end if; 
    end process;


    ap_phi_mux_crc_V_90_phi_fu_424_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_90_reg_421, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_90_phi_fu_424_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_90_phi_fu_424_p4 <= crc_V_90_reg_421;
        end if; 
    end process;


    ap_phi_mux_crc_V_9_phi_fu_655_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_9_reg_652, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_9_phi_fu_655_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_crc_V_9_phi_fu_655_p4 <= crc_V_9_reg_652;
        end if; 
    end process;


    ap_phi_mux_crc_V_phi_fu_754_p4_assign_proc : process(ap_CS_fsm_state1, crc_V_78, crc_V_reg_751, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_crc_V_phi_fu_754_p4 <= crc_V_78;
        else 
            ap_phi_mux_crc_V_phi_fu_754_p4 <= crc_V_reg_751;
        end if; 
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, k_fu_128)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i <= k_fu_128;
        end if; 
    end process;

    crc_V_10_out <= ap_phi_mux_crc_V_10_phi_fu_644_p4;

    crc_V_10_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_10_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_11_out <= ap_phi_mux_crc_V_11_phi_fu_633_p4;

    crc_V_11_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_11_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_14_out <= ap_phi_mux_crc_V_14_phi_fu_600_p4;

    crc_V_14_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_14_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_15_out <= ap_phi_mux_crc_V_15_phi_fu_589_p4;

    crc_V_15_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_15_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_17_out <= ap_phi_mux_crc_V_17_phi_fu_567_p4;

    crc_V_17_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_17_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_18_out <= ap_phi_mux_crc_V_18_phi_fu_556_p4;

    crc_V_18_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_18_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_1_out <= ap_phi_mux_crc_V_1_phi_fu_743_p4;

    crc_V_1_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_21_out <= ap_phi_mux_crc_V_21_phi_fu_523_p4;

    crc_V_21_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_21_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_21_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_22_out <= ap_phi_mux_crc_V_22_phi_fu_512_p4;

    crc_V_22_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_22_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_22_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_28_out <= ap_phi_mux_crc_V_28_phi_fu_446_p4;

    crc_V_28_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_28_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_28_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_2_out <= ap_phi_mux_crc_V_2_phi_fu_732_p4;

    crc_V_2_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_2_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_31_out <= ap_phi_mux_crc_V_31_phi_fu_413_p4;

    crc_V_31_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_31_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_31_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_38_fu_1042_p2 <= (or_ln27_7_fu_1036_p2 xor ap_phi_mux_crc_V_90_phi_fu_424_p4);
    crc_V_39_fu_1882_p2 <= (xor_ln27_31_fu_1876_p2 and ap_phi_mux_crc_V_phi_fu_754_p4);
    crc_V_3_out <= ap_phi_mux_crc_V_3_phi_fu_721_p4;

    crc_V_3_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_3_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_40_fu_1868_p3 <= 
        xor_ln1499_fu_814_p2 when (and_ln27_7_fu_1238_p2(0) = '1') else 
        and_ln27_14_fu_1862_p2;
    crc_V_41_fu_1848_p3 <= 
        xor_ln1499_7_fu_856_p2 when (and_ln27_5_fu_1190_p2(0) = '1') else 
        and_ln27_13_fu_1842_p2;
    crc_V_42_fu_1828_p3 <= 
        xor_ln1499_11_fu_880_p2 when (and_ln27_4_fu_1148_p2(0) = '1') else 
        and_ln27_12_fu_1822_p2;
    crc_V_43_fu_1808_p3 <= 
        xor_ln1499_15_fu_904_p2 when (and_ln27_3_fu_1106_p2(0) = '1') else 
        and_ln27_11_fu_1802_p2;
    crc_V_44_fu_1788_p3 <= 
        xor_ln1499_16_fu_910_p2 when (and_ln27_2_fu_1100_p2(0) = '1') else 
        and_ln27_10_fu_1782_p2;
    crc_V_45_fu_1770_p2 <= (xor_ln27_25_fu_1764_p2 and select_ln27_24_fu_1756_p3);
    crc_V_46_fu_1740_p3 <= 
        ret_V_fu_826_p2 when (or_ln27_21_fu_1244_p2(0) = '1') else 
        select_ln27_21_fu_1732_p3;
    crc_V_47_fu_1714_p2 <= (or_ln27_62_fu_1708_p2 xor ap_phi_mux_crc_V_8_phi_fu_666_p4);
    crc_V_48_fu_1676_p3 <= 
        xor_ln1499_12_fu_886_p2 when (and_ln27_4_fu_1148_p2(0) = '1') else 
        select_ln27_19_fu_1668_p3;
    crc_V_49_fu_1660_p3 <= 
        xor_ln1499_3_fu_832_p2 when (or_ln27_48_fu_1492_p2(0) = '1') else 
        select_ln27_17_fu_1652_p3;
    crc_V_4_out <= ap_phi_mux_crc_V_4_phi_fu_710_p4;

    crc_V_4_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_4_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_50_fu_1644_p3 <= 
        xor_ln1499_8_fu_862_p2 when (or_ln27_58_fu_1630_p2(0) = '1') else 
        select_ln27_15_fu_1636_p3;
    crc_V_51_fu_1622_p3 <= 
        ret_V_1_fu_892_p2 when (or_ln27_15_fu_1160_p2(0) = '1') else 
        select_ln27_13_fu_1614_p3;
    crc_V_52_fu_1608_p2 <= (or_ln27_57_fu_1602_p2 xor ap_phi_mux_crc_V_72_phi_fu_611_p4);
    crc_V_53_fu_1578_p2 <= (or_ln27_54_fu_1572_p2 xor ap_phi_mux_crc_V_14_phi_fu_600_p4);
    crc_V_54_fu_1534_p3 <= 
        xor_ln1499_9_fu_868_p2 when (or_ln27_25_fu_1284_p2(0) = '1') else 
        select_ln27_11_fu_1526_p3;
    crc_V_55_fu_1518_p3 <= 
        ret_V_2_fu_898_p2 when (or_ln27_15_fu_1160_p2(0) = '1') else 
        select_ln27_9_fu_1510_p3;
    crc_V_56_fu_1504_p2 <= (or_ln27_49_fu_1498_p2 xor ap_phi_mux_crc_V_17_phi_fu_567_p4);
    crc_V_57_fu_1448_p3 <= 
        xor_ln1499_4_fu_838_p2 when (or_ln27_42_fu_1442_p2(0) = '1') else 
        ap_phi_mux_crc_V_18_phi_fu_556_p4;
    crc_V_58_fu_1434_p3 <= 
        ret_V_3_fu_844_p2 when (or_ln27_41_fu_1428_p2(0) = '1') else 
        select_ln27_6_fu_1420_p3;
    crc_V_59_fu_1414_p2 <= (or_ln27_40_fu_1408_p2 xor ap_phi_mux_crc_V_75_phi_fu_534_p4);
    crc_V_5_out <= ap_phi_mux_crc_V_5_phi_fu_699_p4;

    crc_V_5_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_5_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_60_fu_1366_p2 <= (or_ln27_34_fu_1360_p2 xor ap_phi_mux_crc_V_21_phi_fu_523_p4);
    crc_V_61_fu_1310_p3 <= 
        xor_ln1499_10_fu_874_p2 when (or_ln27_27_fu_1304_p2(0) = '1') else 
        select_ln27_4_fu_1296_p3;
    crc_V_62_fu_1276_p3 <= 
        ret_V_4_fu_850_p2 when (or_ln27_24_fu_1262_p2(0) = '1') else 
        select_ln27_2_fu_1268_p3;
    crc_V_63_fu_1232_p2 <= (ap_phi_mux_crc_V_77_phi_fu_490_p4 xor and_ln27_6_fu_1226_p2);
    crc_V_64_fu_1214_p2 <= (or_ln27_20_fu_1208_p2 xor ap_phi_mux_crc_V_86_phi_fu_479_p4);
    crc_V_65_fu_1172_p2 <= (or_ln27_16_fu_1166_p2 xor ap_phi_mux_crc_V_87_phi_fu_468_p4);
    crc_V_66_fu_1130_p2 <= (or_ln27_12_fu_1124_p2 xor ap_phi_mux_crc_V_88_phi_fu_457_p4);
    crc_V_67_fu_1082_p2 <= (xor_ln27_4_fu_1076_p2 xor ap_phi_mux_crc_V_28_phi_fu_446_p4);
    crc_V_68_fu_1062_p3 <= 
        ret_V_5_fu_916_p2 when (and_ln27_fu_1030_p2(0) = '1') else 
        select_ln27_fu_1054_p3;
    crc_V_69_fu_1018_p2 <= (xor_ln27_fu_1012_p2 xor ap_phi_mux_crc_V_31_phi_fu_413_p4);
    crc_V_6_out <= ap_phi_mux_crc_V_6_phi_fu_688_p4;

    crc_V_6_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_6_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_86_out <= ap_phi_mux_crc_V_70_phi_fu_677_p4;

    crc_V_86_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_86_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_86_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_87_out <= ap_phi_mux_crc_V_71_phi_fu_622_p4;

    crc_V_87_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_87_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_87_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_88_out <= ap_phi_mux_crc_V_72_phi_fu_611_p4;

    crc_V_88_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_88_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_88_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_89_out <= ap_phi_mux_crc_V_73_phi_fu_578_p4;

    crc_V_89_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_89_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_89_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_8_out <= ap_phi_mux_crc_V_8_phi_fu_666_p4;

    crc_V_8_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_8_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_90_out <= ap_phi_mux_crc_V_74_phi_fu_545_p4;

    crc_V_90_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_90_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_90_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_91_out <= ap_phi_mux_crc_V_75_phi_fu_534_p4;

    crc_V_91_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_91_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_91_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_92_out <= ap_phi_mux_crc_V_76_phi_fu_501_p4;

    crc_V_92_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_92_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_92_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_93_out <= ap_phi_mux_crc_V_77_phi_fu_490_p4;

    crc_V_93_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_93_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_93_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_94_out <= ap_phi_mux_crc_V_86_phi_fu_479_p4;

    crc_V_94_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_94_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_94_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_95_out <= ap_phi_mux_crc_V_87_phi_fu_468_p4;

    crc_V_95_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_95_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_95_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_96_out <= ap_phi_mux_crc_V_88_phi_fu_457_p4;

    crc_V_96_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_96_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_96_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_97_out <= ap_phi_mux_crc_V_89_phi_fu_435_p4;

    crc_V_97_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_97_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_97_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_98_out <= ap_phi_mux_crc_V_90_phi_fu_424_p4;

    crc_V_98_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_98_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_98_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_9_out <= ap_phi_mux_crc_V_9_phi_fu_655_p4;

    crc_V_9_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_9_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_V_out <= ap_phi_mux_crc_V_phi_fu_754_p4;

    crc_V_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln21_fu_770_p2, ap_start_int)
    begin
        if (((icmp_ln21_fu_770_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            crc_V_out_ap_vld <= ap_const_logic_1;
        else 
            crc_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln21_fu_770_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv4_8) else "0";
    icmp_ln27_1_fu_928_p2 <= "1" when (trunc_ln1019_fu_782_p1 = ap_const_lv3_1) else "0";
    icmp_ln27_2_fu_934_p2 <= "1" when (trunc_ln1019_fu_782_p1 = ap_const_lv3_2) else "0";
    icmp_ln27_3_fu_940_p2 <= "1" when (trunc_ln1019_fu_782_p1 = ap_const_lv3_3) else "0";
    icmp_ln27_4_fu_946_p2 <= "1" when (trunc_ln1019_fu_782_p1 = ap_const_lv3_4) else "0";
    icmp_ln27_5_fu_952_p2 <= "1" when (trunc_ln1019_fu_782_p1 = ap_const_lv3_5) else "0";
    icmp_ln27_6_fu_958_p2 <= "1" when (trunc_ln1019_fu_782_p1 = ap_const_lv3_6) else "0";
    icmp_ln27_7_fu_1220_p2 <= "0" when (trunc_ln1019_fu_782_p1 = ap_const_lv3_2) else "1";
    icmp_ln27_fu_922_p2 <= "1" when (trunc_ln1019_fu_782_p1 = ap_const_lv3_0) else "0";
    or_ln27_10_fu_1112_p2 <= (xor_ln27_6_fu_1094_p2 or and_ln27_2_fu_1100_p2);
    or_ln27_11_fu_1118_p2 <= (and_ln27_fu_1030_p2 or and_ln27_3_fu_1106_p2);
    or_ln27_12_fu_1124_p2 <= (or_ln27_11_fu_1118_p2 or or_ln27_10_fu_1112_p2);
    or_ln27_13_fu_1136_p2 <= (or_ln27_1_fu_976_p2 or icmp_ln27_4_fu_946_p2);
    or_ln27_14_fu_1154_p2 <= (xor_ln27_8_fu_1142_p2 or and_ln27_3_fu_1106_p2);
    or_ln27_15_fu_1160_p2 <= (and_ln27_fu_1030_p2 or and_ln27_4_fu_1148_p2);
    or_ln27_16_fu_1166_p2 <= (or_ln27_15_fu_1160_p2 or or_ln27_14_fu_1154_p2);
    or_ln27_17_fu_1178_p2 <= (or_ln27_fu_970_p2 or icmp_ln27_3_fu_940_p2);
    or_ln27_18_fu_1196_p2 <= (xor_ln27_10_fu_1184_p2 or and_ln27_4_fu_1148_p2);
    or_ln27_19_fu_1202_p2 <= (and_ln27_fu_1030_p2 or and_ln27_5_fu_1190_p2);
    or_ln27_1_fu_976_p2 <= (or_ln27_fu_970_p2 or icmp_ln27_1_fu_928_p2);
    or_ln27_20_fu_1208_p2 <= (or_ln27_19_fu_1202_p2 or or_ln27_18_fu_1196_p2);
    or_ln27_21_fu_1244_p2 <= (and_ln27_fu_1030_p2 or and_ln27_7_fu_1238_p2);
    or_ln27_22_fu_1250_p2 <= (and_ln27_4_fu_1148_p2 or and_ln27_3_fu_1106_p2);
    or_ln27_23_fu_1256_p2 <= (and_ln27_2_fu_1100_p2 or and_ln27_1_fu_1048_p2);
    or_ln27_24_fu_1262_p2 <= (or_ln27_22_fu_1250_p2 or or_ln27_21_fu_1244_p2);
    or_ln27_25_fu_1284_p2 <= (and_ln27_5_fu_1190_p2 or and_ln27_4_fu_1148_p2);
    or_ln27_26_fu_1290_p2 <= (and_ln27_3_fu_1106_p2 or and_ln27_2_fu_1100_p2);
    or_ln27_27_fu_1304_p2 <= (or_ln27_26_fu_1290_p2 or or_ln27_25_fu_1284_p2);
    or_ln27_28_fu_1318_p2 <= (xor_ln23_fu_964_p2 or icmp_ln27_6_fu_958_p2);
    or_ln27_29_fu_1324_p2 <= (or_ln27_28_fu_1318_p2 or icmp_ln27_5_fu_952_p2);
    or_ln27_2_fu_982_p2 <= (or_ln27_1_fu_976_p2 or icmp_ln27_2_fu_934_p2);
    or_ln27_30_fu_1336_p2 <= (xor_ln27_13_fu_1330_p2 or and_ln27_3_fu_1106_p2);
    or_ln27_31_fu_1342_p2 <= (or_ln27_30_fu_1336_p2 or and_ln27_2_fu_1100_p2);
    or_ln27_32_fu_1348_p2 <= (and_ln27_7_fu_1238_p2 or and_ln27_5_fu_1190_p2);
    or_ln27_33_fu_1354_p2 <= (or_ln27_32_fu_1348_p2 or and_ln27_4_fu_1148_p2);
    or_ln27_34_fu_1360_p2 <= (or_ln27_33_fu_1354_p2 or or_ln27_31_fu_1342_p2);
    or_ln27_35_fu_1372_p2 <= (xor_ln23_fu_964_p2 or icmp_ln27_5_fu_952_p2);
    or_ln27_36_fu_1378_p2 <= (or_ln27_35_fu_1372_p2 or icmp_ln27_4_fu_946_p2);
    or_ln27_37_fu_1390_p2 <= (xor_ln27_15_fu_1384_p2 or and_ln27_4_fu_1148_p2);
    or_ln27_38_fu_1396_p2 <= (or_ln27_37_fu_1390_p2 or and_ln27_3_fu_1106_p2);
    or_ln27_39_fu_1402_p2 <= (or_ln27_21_fu_1244_p2 or and_ln27_5_fu_1190_p2);
    or_ln27_3_fu_988_p2 <= (or_ln27_2_fu_982_p2 or icmp_ln27_3_fu_940_p2);
    or_ln27_40_fu_1408_p2 <= (or_ln27_39_fu_1402_p2 or or_ln27_38_fu_1396_p2);
    or_ln27_41_fu_1428_p2 <= (or_ln27_25_fu_1284_p2 or or_ln27_21_fu_1244_p2);
    or_ln27_42_fu_1442_p2 <= (or_ln27_32_fu_1348_p2 or or_ln27_23_fu_1256_p2);
    or_ln27_43_fu_1456_p2 <= (xor_ln23_fu_964_p2 or icmp_ln27_2_fu_934_p2);
    or_ln27_44_fu_1462_p2 <= (or_ln27_43_fu_1456_p2 or icmp_ln27_1_fu_928_p2);
    or_ln27_45_fu_1468_p2 <= (icmp_ln27_6_fu_958_p2 or icmp_ln27_5_fu_952_p2);
    or_ln27_46_fu_1474_p2 <= (or_ln27_45_fu_1468_p2 or or_ln27_44_fu_1462_p2);
    or_ln27_47_fu_1486_p2 <= (xor_ln27_17_fu_1480_p2 or and_ln27_2_fu_1100_p2);
    or_ln27_48_fu_1492_p2 <= (and_ln27_7_fu_1238_p2 or and_ln27_3_fu_1106_p2);
    or_ln27_49_fu_1498_p2 <= (or_ln27_48_fu_1492_p2 or or_ln27_47_fu_1486_p2);
    or_ln27_4_fu_994_p2 <= (icmp_ln27_5_fu_952_p2 or icmp_ln27_4_fu_946_p2);
    or_ln27_50_fu_1542_p2 <= (icmp_ln27_3_fu_940_p2 or icmp_ln27_2_fu_934_p2);
    or_ln27_51_fu_1548_p2 <= (xor_ln23_fu_964_p2 or or_ln27_50_fu_1542_p2);
    or_ln27_52_fu_1554_p2 <= (or_ln27_51_fu_1548_p2 or or_ln27_45_fu_1468_p2);
    or_ln27_53_fu_1566_p2 <= (xor_ln27_19_fu_1560_p2 or and_ln27_2_fu_1100_p2);
    or_ln27_54_fu_1572_p2 <= (or_ln27_53_fu_1566_p2 or or_ln27_32_fu_1348_p2);
    or_ln27_55_fu_1584_p2 <= (or_ln27_4_fu_994_p2 or or_ln27_44_fu_1462_p2);
    or_ln27_56_fu_1596_p2 <= (xor_ln27_21_fu_1590_p2 or and_ln27_3_fu_1106_p2);
    or_ln27_57_fu_1602_p2 <= (or_ln27_56_fu_1596_p2 or or_ln27_21_fu_1244_p2);
    or_ln27_58_fu_1630_p2 <= (and_ln27_5_fu_1190_p2 or and_ln27_2_fu_1100_p2);
    or_ln27_59_fu_1684_p2 <= (or_ln27_17_fu_1178_p2 or icmp_ln27_4_fu_946_p2);
    or_ln27_5_fu_1000_p2 <= (or_ln27_4_fu_994_p2 or or_ln27_3_fu_988_p2);
    or_ln27_60_fu_1690_p2 <= (or_ln27_59_fu_1684_p2 or or_ln27_45_fu_1468_p2);
    or_ln27_61_fu_1702_p2 <= (xor_ln27_23_fu_1696_p2 or and_ln27_5_fu_1190_p2);
    or_ln27_62_fu_1708_p2 <= (or_ln27_61_fu_1702_p2 or and_ln27_4_fu_1148_p2);
    or_ln27_63_fu_1720_p2 <= (or_ln27_51_fu_1548_p2 or or_ln27_4_fu_994_p2);
    or_ln27_6_fu_1006_p2 <= (or_ln27_5_fu_1000_p2 or icmp_ln27_6_fu_958_p2);
    or_ln27_7_fu_1036_p2 <= (xor_ln27_2_fu_1024_p2 or and_ln27_fu_1030_p2);
    or_ln27_8_fu_1070_p2 <= (or_ln27_3_fu_988_p2 or icmp_ln27_6_fu_958_p2);
    or_ln27_9_fu_1088_p2 <= (or_ln27_2_fu_982_p2 or icmp_ln27_5_fu_952_p2);
    or_ln27_fu_970_p2 <= (xor_ln23_fu_964_p2 or icmp_ln27_fu_922_p2);
    ret_V_1_fu_892_p2 <= (ap_phi_mux_crc_V_71_phi_fu_622_p4 xor ap_const_lv1_1);
    ret_V_2_fu_898_p2 <= (ap_phi_mux_crc_V_73_phi_fu_578_p4 xor ap_const_lv1_1);
    ret_V_3_fu_844_p2 <= (ap_phi_mux_crc_V_74_phi_fu_545_p4 xor ap_const_lv1_1);
    ret_V_4_fu_850_p2 <= (ap_phi_mux_crc_V_76_phi_fu_501_p4 xor ap_const_lv1_1);
    ret_V_5_fu_916_p2 <= (ap_phi_mux_crc_V_89_phi_fu_435_p4 xor ap_const_lv1_1);
    ret_V_fu_826_p2 <= (ap_phi_mux_crc_V_70_phi_fu_677_p4 xor ap_const_lv1_1);
    select_ln27_11_fu_1526_p3 <= 
        xor_ln1499_9_fu_868_p2 when (and_ln27_1_fu_1048_p2(0) = '1') else 
        ap_phi_mux_crc_V_15_phi_fu_589_p4;
    select_ln27_13_fu_1614_p3 <= 
        ret_V_1_fu_892_p2 when (and_ln27_1_fu_1048_p2(0) = '1') else 
        ap_phi_mux_crc_V_71_phi_fu_622_p4;
    select_ln27_15_fu_1636_p3 <= 
        xor_ln1499_8_fu_862_p2 when (and_ln27_1_fu_1048_p2(0) = '1') else 
        ap_phi_mux_crc_V_11_phi_fu_633_p4;
    select_ln27_17_fu_1652_p3 <= 
        xor_ln1499_3_fu_832_p2 when (and_ln27_2_fu_1100_p2(0) = '1') else 
        ap_phi_mux_crc_V_10_phi_fu_644_p4;
    select_ln27_19_fu_1668_p3 <= 
        xor_ln1499_12_fu_886_p2 when (and_ln27_3_fu_1106_p2(0) = '1') else 
        ap_phi_mux_crc_V_9_phi_fu_655_p4;
    select_ln27_21_fu_1732_p3 <= 
        ret_V_fu_826_p2 when (and_ln27_5_fu_1190_p2(0) = '1') else 
        and_ln27_8_fu_1726_p2;
    select_ln27_23_fu_1748_p3 <= 
        xor_ln1499_1_fu_820_p2 when (and_ln27_1_fu_1048_p2(0) = '1') else 
        ap_phi_mux_crc_V_6_phi_fu_688_p4;
    select_ln27_24_fu_1756_p3 <= 
        xor_ln1499_1_fu_820_p2 when (and_ln27_7_fu_1238_p2(0) = '1') else 
        select_ln27_23_fu_1748_p3;
    select_ln27_2_fu_1268_p3 <= 
        ret_V_4_fu_850_p2 when (or_ln27_23_fu_1256_p2(0) = '1') else 
        ap_phi_mux_crc_V_76_phi_fu_501_p4;
    select_ln27_4_fu_1296_p3 <= 
        xor_ln1499_10_fu_874_p2 when (and_ln27_1_fu_1048_p2(0) = '1') else 
        ap_phi_mux_crc_V_22_phi_fu_512_p4;
    select_ln27_6_fu_1420_p3 <= 
        ret_V_3_fu_844_p2 when (and_ln27_1_fu_1048_p2(0) = '1') else 
        ap_phi_mux_crc_V_74_phi_fu_545_p4;
    select_ln27_9_fu_1510_p3 <= 
        ret_V_2_fu_898_p2 when (and_ln27_3_fu_1106_p2(0) = '1') else 
        ap_phi_mux_crc_V_73_phi_fu_578_p4;
    select_ln27_fu_1054_p3 <= 
        ret_V_5_fu_916_p2 when (and_ln27_1_fu_1048_p2(0) = '1') else 
        ap_phi_mux_crc_V_89_phi_fu_435_p4;
    trunc_ln1019_fu_782_p1 <= ap_sig_allocacmp_i(3 - 1 downto 0);
    xor_ln1499_10_fu_874_p2 <= (ap_phi_mux_crc_V_22_phi_fu_512_p4 xor ap_const_lv1_1);
    xor_ln1499_11_fu_880_p2 <= (ap_phi_mux_crc_V_3_phi_fu_721_p4 xor ap_const_lv1_1);
    xor_ln1499_12_fu_886_p2 <= (ap_phi_mux_crc_V_9_phi_fu_655_p4 xor ap_const_lv1_1);
    xor_ln1499_15_fu_904_p2 <= (ap_phi_mux_crc_V_4_phi_fu_710_p4 xor ap_const_lv1_1);
    xor_ln1499_16_fu_910_p2 <= (ap_phi_mux_crc_V_5_phi_fu_699_p4 xor ap_const_lv1_1);
    xor_ln1499_1_fu_820_p2 <= (ap_phi_mux_crc_V_6_phi_fu_688_p4 xor ap_const_lv1_1);
    xor_ln1499_3_fu_832_p2 <= (ap_phi_mux_crc_V_10_phi_fu_644_p4 xor ap_const_lv1_1);
    xor_ln1499_4_fu_838_p2 <= (ap_phi_mux_crc_V_18_phi_fu_556_p4 xor ap_const_lv1_1);
    xor_ln1499_7_fu_856_p2 <= (ap_phi_mux_crc_V_2_phi_fu_732_p4 xor ap_const_lv1_1);
    xor_ln1499_8_fu_862_p2 <= (ap_phi_mux_crc_V_11_phi_fu_633_p4 xor ap_const_lv1_1);
    xor_ln1499_9_fu_868_p2 <= (ap_phi_mux_crc_V_15_phi_fu_589_p4 xor ap_const_lv1_1);
    xor_ln1499_fu_814_p2 <= (ap_phi_mux_crc_V_1_phi_fu_743_p4 xor ap_const_lv1_1);
    xor_ln23_fu_964_p2 <= (ap_const_lv1_1 xor and_ln23_fu_808_p2);
    xor_ln27_10_fu_1184_p2 <= (or_ln27_17_fu_1178_p2 xor ap_const_lv1_1);
    xor_ln27_13_fu_1330_p2 <= (or_ln27_29_fu_1324_p2 xor ap_const_lv1_1);
    xor_ln27_15_fu_1384_p2 <= (or_ln27_36_fu_1378_p2 xor ap_const_lv1_1);
    xor_ln27_17_fu_1480_p2 <= (or_ln27_46_fu_1474_p2 xor ap_const_lv1_1);
    xor_ln27_19_fu_1560_p2 <= (or_ln27_52_fu_1554_p2 xor ap_const_lv1_1);
    xor_ln27_21_fu_1590_p2 <= (or_ln27_55_fu_1584_p2 xor ap_const_lv1_1);
    xor_ln27_23_fu_1696_p2 <= (or_ln27_60_fu_1690_p2 xor ap_const_lv1_1);
    xor_ln27_25_fu_1764_p2 <= (ap_const_lv1_1 xor and_ln27_fu_1030_p2);
    xor_ln27_26_fu_1776_p2 <= (ap_const_lv1_1 xor and_ln27_1_fu_1048_p2);
    xor_ln27_27_fu_1796_p2 <= (ap_const_lv1_1 xor and_ln27_2_fu_1100_p2);
    xor_ln27_28_fu_1816_p2 <= (ap_const_lv1_1 xor and_ln27_3_fu_1106_p2);
    xor_ln27_29_fu_1836_p2 <= (ap_const_lv1_1 xor and_ln27_4_fu_1148_p2);
    xor_ln27_2_fu_1024_p2 <= (or_ln27_5_fu_1000_p2 xor ap_const_lv1_1);
    xor_ln27_30_fu_1856_p2 <= (ap_const_lv1_1 xor and_ln27_5_fu_1190_p2);
    xor_ln27_31_fu_1876_p2 <= (ap_const_lv1_1 xor and_ln27_7_fu_1238_p2);
    xor_ln27_4_fu_1076_p2 <= (or_ln27_8_fu_1070_p2 xor ap_const_lv1_1);
    xor_ln27_6_fu_1094_p2 <= (or_ln27_9_fu_1088_p2 xor ap_const_lv1_1);
    xor_ln27_8_fu_1142_p2 <= (or_ln27_13_fu_1136_p2 xor ap_const_lv1_1);
    xor_ln27_fu_1012_p2 <= (or_ln27_6_fu_1006_p2 xor ap_const_lv1_1);
end behav;
